/* Pinyin-Trainer – Wortschatz A1
 * Format: [hanzi, pinyin, deutsch, wortart, beispielPinyin?, beispielDe?, beispielHanzi?]
 * Wortart: n=Nomen v=Verb a=Adjektiv d=Adverb p=Partikel s=Sonstiges
 */
VokabelDaten.add('A1', {

  begruessung: [
    ['你好', 'nǐ hǎo', 'hallo', 's', 'Nǐ hǎo, wǒ jiào Mǎkè.', 'Hallo, ich heiße Mark.', '你好，我叫马克。'],
    ['您好', 'nín hǎo', 'guten Tag (höflich)', 's', 'Nín hǎo, qǐng zuò.', 'Guten Tag, bitte setzen Sie sich.', '您好，请坐。'],
    ['早上好', 'zǎoshang hǎo', 'guten Morgen', 's'],
    ['晚上好', 'wǎnshang hǎo', 'guten Abend', 's'],
    ['再见', 'zàijiàn', 'auf Wiedersehen', 's', 'Míngtiān jiàn, zàijiàn!', 'Bis morgen, auf Wiedersehen!', '明天见，再见！'],
    ['谢谢', 'xièxie', 'danke', 'v', 'Xièxie nǐ de bāngmáng.', 'Danke für deine Hilfe.', '谢谢你的帮忙。'],
    ['不客气', 'bú kèqi', 'gern geschehen', 's'],
    ['对不起', 'duìbuqǐ', 'Entschuldigung', 's', 'Duìbuqǐ, wǒ lái wǎn le.', 'Entschuldigung, ich bin zu spät gekommen.', '对不起，我来晚了。'],
    ['没关系', 'méi guānxi', 'macht nichts', 's'],
    ['请', 'qǐng', 'bitte (auffordernd)', 'v', 'Qǐng hē chá.', 'Bitte trinken Sie Tee.', '请喝茶。'],
    ['请问', 'qǐngwèn', 'darf ich fragen', 'v', 'Qǐngwèn, cèsuǒ zài nǎr?', 'Entschuldigung, wo ist die Toilette?', '请问，厕所在哪儿？'],
    ['是', 'shì', 'sein', 'v', 'Wǒ shì Déguó rén.', 'Ich bin Deutscher.', '我是德国人。'],
    ['我', 'wǒ', 'ich', 's'],
    ['你', 'nǐ', 'du', 's'],
    ['您', 'nín', 'Sie (höflich)', 's'],
    ['他', 'tā', 'er', 's'],
    ['她', 'tā', 'sie (Einzahl)', 's'],
    ['我们', 'wǒmen', 'wir', 's'],
    ['你们', 'nǐmen', 'ihr', 's'],
    ['他们', 'tāmen', 'sie (Mehrzahl)', 's'],
    ['叫', 'jiào', 'heißen', 'v', 'Nǐ jiào shénme míngzi?', 'Wie heißt du?', '你叫什么名字？'],
    ['名字', 'míngzi', 'Name', 'n'],
    ['认识', 'rènshi', 'kennenlernen', 'v', 'Rènshi nǐ hěn gāoxìng.', 'Ich freue mich, dich kennenzulernen.', '认识你很高兴。'],
    ['高兴', 'gāoxìng', 'erfreut', 'a'],
    ['很', 'hěn', 'sehr', 'd', 'Zhōngwén hěn yǒuyìsi.', 'Chinesisch ist sehr interessant.', '中文很有意思。'],
    ['吗', 'ma', 'Fragepartikel (Ja/Nein)', 'p', 'Nǐ shì lǎoshī ma?', 'Bist du Lehrer?', '你是老师吗？'],
    ['呢', 'ne', 'Rückfragepartikel', 'p', 'Wǒ hěn hǎo, nǐ ne?', 'Mir geht es gut, und dir?', '我很好，你呢？'],
    ['好', 'hǎo', 'gut', 'a'],
    ['中国', 'Zhōngguó', 'China', 'n'],
    ['德国', 'Déguó', 'Deutschland', 'n'],
    ['人', 'rén', 'Mensch, Person', 'n'],
    ['说', 'shuō', 'sprechen, sagen', 'v', 'Tā shuō de hěn màn.', 'Er spricht sehr langsam.', '他说得很慢。'],
    ['汉语', 'Hànyǔ', 'Chinesisch (Sprache)', 'n', 'Wǒ xuéxí Hànyǔ.', 'Ich lerne Chinesisch.', '我学习汉语。'],
    ['中文', 'Zhōngwén', 'Chinesisch (Sprache/Schrift)', 'n'],
    ['德语', 'Déyǔ', 'Deutsch (Sprache)', 'n'],
    ['英语', 'Yīngyǔ', 'Englisch (Sprache)', 'n'],
    ['会', 'huì', 'können (erlernte Fähigkeit)', 'v', 'Wǒ huì shuō yìdiǎnr Hànyǔ.', 'Ich kann ein bisschen Chinesisch.', '我会说一点儿汉语。'],
    ['一点儿', 'yìdiǎnr', 'ein bisschen', 's'],
    ['不', 'bù', 'nicht', 'd', 'Wǒ bù chī ròu.', 'Ich esse kein Fleisch.', '我不吃肉。'],
    ['也', 'yě', 'auch', 'd', 'Wǒ yě shì xuésheng.', 'Ich bin auch Schüler.', '我也是学生。']
  ],

  zahlen: [
    ['一', 'yī', 'eins', 's'],
    ['二', 'èr', 'zwei', 's'],
    ['三', 'sān', 'drei', 's'],
    ['四', 'sì', 'vier', 's'],
    ['五', 'wǔ', 'fünf', 's'],
    ['六', 'liù', 'sechs', 's'],
    ['七', 'qī', 'sieben', 's'],
    ['八', 'bā', 'acht', 's'],
    ['九', 'jiǔ', 'neun', 's'],
    ['十', 'shí', 'zehn', 's'],
    ['零', 'líng', 'null', 's'],
    ['百', 'bǎi', 'hundert', 's', 'Yìbǎi kuài qián.', 'Hundert Yuan.', '一百块钱。'],
    ['千', 'qiān', 'tausend', 's'],
    ['万', 'wàn', 'zehntausend', 's'],
    ['两', 'liǎng', 'zwei (vor Zähleinheit)', 's', 'Wǒ yào liǎng ge píngguǒ.', 'Ich möchte zwei Äpfel.', '我要两个苹果。'],
    ['个', 'gè', 'Zähleinheitswort (allgemein)', 'p'],
    ['几', 'jǐ', 'wie viele (kleine Zahl)', 's', 'Xiànzài jǐ diǎn?', 'Wie spät ist es?', '现在几点？'],
    ['多少', 'duōshao', 'wie viel', 's'],
    ['第一', 'dì-yī', 'der/die/das erste', 's'],
    ['点', 'diǎn', 'Uhr (volle Stunde)', 'n', 'Wǒ qī diǎn qǐchuáng.', 'Ich stehe um sieben Uhr auf.', '我七点起床。'],
    ['分', 'fēn', 'Minute', 'n'],
    ['半', 'bàn', 'halb', 's', 'Sān diǎn bàn.', 'Halb vier.', '三点半。'],
    ['小时', 'xiǎoshí', 'Stunde (Dauer)', 'n'],
    ['分钟', 'fēnzhōng', 'Minute (Dauer)', 'n'],
    ['天', 'tiān', 'Tag', 'n'],
    ['今天', 'jīntiān', 'heute', 'n', 'Jīntiān tiānqì hěn hǎo.', 'Heute ist das Wetter sehr gut.', '今天天气很好。'],
    ['明天', 'míngtiān', 'morgen', 'n'],
    ['昨天', 'zuótiān', 'gestern', 'n'],
    ['星期', 'xīngqī', 'Woche', 'n', 'Jīntiān xīngqī jǐ?', 'Welcher Wochentag ist heute?', '今天星期几？'],
    ['星期一', 'xīngqīyī', 'Montag', 'n'],
    ['星期天', 'xīngqītiān', 'Sonntag', 'n'],
    ['月', 'yuè', 'Monat', 'n'],
    ['年', 'nián', 'Jahr', 'n'],
    ['号', 'hào', 'Tag (im Datum)', 'n', 'Jīntiān wǔ yuè shí hào.', 'Heute ist der 10. Mai.', '今天五月十号。'],
    ['现在', 'xiànzài', 'jetzt', 'd'],
    ['早上', 'zǎoshang', 'Morgen', 'n'],
    ['上午', 'shàngwǔ', 'Vormittag', 'n'],
    ['中午', 'zhōngwǔ', 'Mittag', 'n'],
    ['下午', 'xiàwǔ', 'Nachmittag', 'n'],
    ['晚上', 'wǎnshang', 'Abend', 'n'],
    ['时候', 'shíhou', 'Zeitpunkt', 'n', 'Nǐ shénme shíhou lái?', 'Wann kommst du?', '你什么时候来？'],
    ['时间', 'shíjiān', 'Zeit', 'n']
  ],

  familie: [
    ['家', 'jiā', 'Familie, Zuhause', 'n', 'Wǒ jiā yǒu sì ge rén.', 'In meiner Familie sind vier Personen.', '我家有四个人。'],
    ['爸爸', 'bàba', 'Vater', 'n'],
    ['妈妈', 'māma', 'Mutter', 'n'],
    ['儿子', 'érzi', 'Sohn', 'n'],
    ['女儿', 'nǚ\'ér', 'Tochter', 'n'],
    ['哥哥', 'gēge', 'älterer Bruder', 'n'],
    ['弟弟', 'dìdi', 'jüngerer Bruder', 'n'],
    ['姐姐', 'jiějie', 'ältere Schwester', 'n'],
    ['妹妹', 'mèimei', 'jüngere Schwester', 'n'],
    ['爷爷', 'yéye', 'Großvater (väterlich)', 'n'],
    ['奶奶', 'nǎinai', 'Großmutter (väterlich)', 'n'],
    ['孩子', 'háizi', 'Kind', 'n'],
    ['男', 'nán', 'männlich', 'a'],
    ['女', 'nǚ', 'weiblich', 'a'],
    ['朋友', 'péngyou', 'Freund, Freundin', 'n', 'Tā shì wǒ de hǎo péngyou.', 'Er ist mein guter Freund.', '他是我的好朋友。'],
    ['男朋友', 'nánpéngyou', 'fester Freund', 'n'],
    ['女朋友', 'nǚpéngyou', 'feste Freundin', 'n'],
    ['爱', 'ài', 'lieben', 'v'],
    ['岁', 'suì', 'Jahre (Alter)', 'n', 'Wǒ èrshí suì.', 'Ich bin zwanzig Jahre alt.', '我二十岁。'],
    ['结婚', 'jiéhūn', 'heiraten', 'v'],
    ['家人', 'jiārén', 'Familienangehörige', 'n'],
    ['的', 'de', 'Possessivpartikel', 'p', 'Zhè shì wǒ de shū.', 'Das ist mein Buch.', '这是我的书。']
  ],

  essen: [
    ['吃', 'chī', 'essen', 'v', 'Wǒ xiǎng chī jiǎozi.', 'Ich möchte Teigtaschen essen.', '我想吃饺子。'],
    ['喝', 'hē', 'trinken', 'v'],
    ['饭', 'fàn', 'Mahlzeit, gekochter Reis', 'n'],
    ['米饭', 'mǐfàn', 'gekochter Reis', 'n'],
    ['面条', 'miàntiáo', 'Nudeln', 'n'],
    ['菜', 'cài', 'Gericht, Gemüse', 'n', 'Zhè ge cài hěn hǎochī.', 'Dieses Gericht ist sehr lecker.', '这个菜很好吃。'],
    ['肉', 'ròu', 'Fleisch', 'n'],
    ['鸡蛋', 'jīdàn', 'Ei', 'n'],
    ['鱼', 'yú', 'Fisch', 'n'],
    ['水', 'shuǐ', 'Wasser', 'n'],
    ['茶', 'chá', 'Tee', 'n'],
    ['咖啡', 'kāfēi', 'Kaffee', 'n'],
    ['牛奶', 'niúnǎi', 'Milch', 'n'],
    ['啤酒', 'píjiǔ', 'Bier', 'n'],
    ['水果', 'shuǐguǒ', 'Obst', 'n'],
    ['苹果', 'píngguǒ', 'Apfel', 'n'],
    ['香蕉', 'xiāngjiāo', 'Banane', 'n'],
    ['面包', 'miànbāo', 'Brot', 'n'],
    ['饺子', 'jiǎozi', 'Teigtaschen', 'n'],
    ['汤', 'tāng', 'Suppe', 'n'],
    ['糖', 'táng', 'Zucker, Süßigkeit', 'n'],
    ['盐', 'yán', 'Salz', 'n'],
    ['饿', 'è', 'hungrig', 'a', 'Wǒ hěn è.', 'Ich habe großen Hunger.', '我很饿。'],
    ['渴', 'kě', 'durstig', 'a'],
    ['好吃', 'hǎochī', 'lecker', 'a'],
    ['饭馆', 'fànguǎn', 'Restaurant', 'n'],
    ['服务员', 'fúwùyuán', 'Kellner, Bedienung', 'n'],
    ['点菜', 'diǎn cài', 'Essen bestellen', 'v'],
    ['早饭', 'zǎofàn', 'Frühstück', 'n'],
    ['午饭', 'wǔfàn', 'Mittagessen', 'n'],
    ['晚饭', 'wǎnfàn', 'Abendessen', 'n'],
    ['筷子', 'kuàizi', 'Essstäbchen', 'n'],
    ['杯子', 'bēizi', 'Becher, Glas', 'n'],
    ['甜', 'tián', 'süß', 'a'],
    ['辣', 'là', 'scharf', 'a', 'Sìchuān cài hěn là.', 'Sichuan-Küche ist sehr scharf.', '四川菜很辣。']
  ],

  einkaufen: [
    ['买', 'mǎi', 'kaufen', 'v', 'Wǒ qù shāngdiàn mǎi dōngxi.', 'Ich gehe in den Laden einkaufen.', '我去商店买东西。'],
    ['卖', 'mài', 'verkaufen', 'v'],
    ['钱', 'qián', 'Geld', 'n'],
    ['块', 'kuài', 'Yuan (Währungseinheit)', 'n'],
    ['毛', 'máo', 'Jiao (Zehntel Yuan)', 'n'],
    ['元', 'yuán', 'Yuan (schriftlich)', 'n'],
    ['贵', 'guì', 'teuer', 'a', 'Tài guì le!', 'Das ist zu teuer!', '太贵了！'],
    ['便宜', 'piányi', 'billig', 'a'],
    ['商店', 'shāngdiàn', 'Geschäft', 'n'],
    ['超市', 'chāoshì', 'Supermarkt', 'n'],
    ['东西', 'dōngxi', 'Ding, Sache', 'n'],
    ['要', 'yào', 'wollen, brauchen', 'v', 'Wǒ yào zhè ge.', 'Ich möchte das hier.', '我要这个。'],
    ['给', 'gěi', 'geben', 'v'],
    ['找', 'zhǎo', 'suchen, herausgeben', 'v'],
    ['多少钱', 'duōshao qián', 'wie viel kostet es', 's', 'Zhè jiàn yīfu duōshao qián?', 'Was kostet dieses Kleidungsstück?', '这件衣服多少钱？'],
    ['付', 'fù', 'bezahlen', 'v'],
    ['一共', 'yígòng', 'insgesamt', 'd'],
    ['太', 'tài', 'zu (übermäßig)', 'd'],
    ['这', 'zhè', 'dies', 's'],
    ['那', 'nà', 'jenes', 's']
  ],

  wohnen: [
    ['房子', 'fángzi', 'Haus', 'n'],
    ['房间', 'fángjiān', 'Zimmer', 'n'],
    ['门', 'mén', 'Tür', 'n'],
    ['窗户', 'chuānghu', 'Fenster', 'n'],
    ['桌子', 'zhuōzi', 'Tisch', 'n', 'Shū zài zhuōzi shàng.', 'Das Buch liegt auf dem Tisch.', '书在桌子上。'],
    ['椅子', 'yǐzi', 'Stuhl', 'n'],
    ['床', 'chuáng', 'Bett', 'n'],
    ['厨房', 'chúfáng', 'Küche', 'n'],
    ['厕所', 'cèsuǒ', 'Toilette', 'n'],
    ['卫生间', 'wèishēngjiān', 'Badezimmer', 'n'],
    ['客厅', 'kètīng', 'Wohnzimmer', 'n'],
    ['住', 'zhù', 'wohnen', 'v', 'Wǒ zhù zài Běijīng.', 'Ich wohne in Peking.', '我住在北京。'],
    ['楼', 'lóu', 'Gebäude, Stockwerk', 'n'],
    ['灯', 'dēng', 'Lampe', 'n'],
    ['电视', 'diànshì', 'Fernseher', 'n'],
    ['冰箱', 'bīngxiāng', 'Kühlschrank', 'n'],
    ['干净', 'gānjìng', 'sauber', 'a'],
    ['睡觉', 'shuìjiào', 'schlafen', 'v'],
    ['起床', 'qǐchuáng', 'aufstehen', 'v'],
    ['地址', 'dìzhǐ', 'Adresse', 'n'],
    ['钥匙', 'yàoshi', 'Schlüssel', 'n']
  ],

  koerper: [
    ['头', 'tóu', 'Kopf', 'n'],
    ['眼睛', 'yǎnjing', 'Auge', 'n'],
    ['耳朵', 'ěrduo', 'Ohr', 'n'],
    ['鼻子', 'bízi', 'Nase', 'n'],
    ['嘴', 'zuǐ', 'Mund', 'n'],
    ['手', 'shǒu', 'Hand', 'n'],
    ['脚', 'jiǎo', 'Fuß', 'n'],
    ['身体', 'shēntǐ', 'Körper', 'n', 'Tā shēntǐ hěn hǎo.', 'Er ist sehr gesund.', '他身体很好。'],
    ['疼', 'téng', 'schmerzen', 'v', 'Wǒ tóu téng.', 'Ich habe Kopfschmerzen.', '我头疼。'],
    ['病', 'bìng', 'Krankheit', 'n'],
    ['生病', 'shēngbìng', 'krank werden', 'v'],
    ['医生', 'yīshēng', 'Arzt', 'n'],
    ['医院', 'yīyuàn', 'Krankenhaus', 'n'],
    ['药', 'yào', 'Medizin', 'n'],
    ['累', 'lèi', 'müde, erschöpft', 'a']
  ],

  kleidung: [
    ['衣服', 'yīfu', 'Kleidung', 'n'],
    ['裤子', 'kùzi', 'Hose', 'n'],
    ['裙子', 'qúnzi', 'Rock', 'n'],
    ['鞋', 'xié', 'Schuh', 'n'],
    ['帽子', 'màozi', 'Mütze, Hut', 'n'],
    ['穿', 'chuān', 'anziehen, tragen', 'v', 'Tā chuān yí jiàn hóng yīfu.', 'Sie trägt ein rotes Kleidungsstück.', '她穿一件红衣服。'],
    ['戴', 'dài', 'tragen (Brille, Hut)', 'v'],
    ['件', 'jiàn', 'Zähleinheit für Kleidung', 'p'],
    ['大', 'dà', 'groß', 'a'],
    ['小', 'xiǎo', 'klein', 'a'],
    ['新', 'xīn', 'neu', 'a'],
    ['旧', 'jiù', 'alt (Gegenstand)', 'a']
  ],

  wetter: [
    ['天气', 'tiānqì', 'Wetter', 'n'],
    ['热', 'rè', 'heiß', 'a'],
    ['冷', 'lěng', 'kalt', 'a', 'Jīntiān hěn lěng.', 'Heute ist es sehr kalt.', '今天很冷。'],
    ['下雨', 'xià yǔ', 'regnen', 'v', 'Míngtiān huì xià yǔ.', 'Morgen wird es regnen.', '明天会下雨。'],
    ['下雪', 'xià xuě', 'schneien', 'v'],
    ['风', 'fēng', 'Wind', 'n'],
    ['太阳', 'tàiyáng', 'Sonne', 'n'],
    ['云', 'yún', 'Wolke', 'n'],
    ['春天', 'chūntiān', 'Frühling', 'n'],
    ['夏天', 'xiàtiān', 'Sommer', 'n'],
    ['秋天', 'qiūtiān', 'Herbst', 'n'],
    ['冬天', 'dōngtiān', 'Winter', 'n'],
    ['度', 'dù', 'Grad', 'n']
  ],

  verkehr: [
    ['车', 'chē', 'Fahrzeug', 'n'],
    ['汽车', 'qìchē', 'Auto', 'n'],
    ['公共汽车', 'gōnggòng qìchē', 'Bus', 'n'],
    ['出租车', 'chūzūchē', 'Taxi', 'n', 'Wǒ zuò chūzūchē qù jīchǎng.', 'Ich fahre mit dem Taxi zum Flughafen.', '我坐出租车去机场。'],
    ['火车', 'huǒchē', 'Zug', 'n'],
    ['飞机', 'fēijī', 'Flugzeug', 'n'],
    ['自行车', 'zìxíngchē', 'Fahrrad', 'n'],
    ['坐', 'zuò', 'sitzen, fahren mit', 'v'],
    ['开车', 'kāichē', 'Auto fahren', 'v'],
    ['走', 'zǒu', 'gehen, laufen', 'v'],
    ['去', 'qù', 'gehen nach, fahren nach', 'v', 'Wǒ míngtiān qù Shànghǎi.', 'Ich fahre morgen nach Shanghai.', '我明天去上海。'],
    ['来', 'lái', 'kommen', 'v'],
    ['机场', 'jīchǎng', 'Flughafen', 'n'],
    ['车站', 'chēzhàn', 'Haltestelle, Bahnhof', 'n'],
    ['票', 'piào', 'Ticket, Fahrkarte', 'n'],
    ['快', 'kuài', 'schnell', 'a'],
    ['慢', 'màn', 'langsam', 'a']
  ],

  richtungen: [
    ['上', 'shàng', 'oben, auf', 's'],
    ['下', 'xià', 'unten, unter', 's'],
    ['里', 'lǐ', 'innen, in', 's'],
    ['外', 'wài', 'außen, außerhalb', 's'],
    ['前面', 'qiánmiàn', 'vorne', 'n'],
    ['后面', 'hòumiàn', 'hinten', 'n'],
    ['上面', 'shàngmiàn', 'oben, darüber', 'n'],
    ['下面', 'xiàmiàn', 'unten, darunter', 'n'],
    ['左边', 'zuǒbiān', 'links', 'n', 'Yínháng zài zuǒbiān.', 'Die Bank ist links.', '银行在左边。'],
    ['右边', 'yòubiān', 'rechts', 'n'],
    ['旁边', 'pángbiān', 'daneben', 'n'],
    ['中间', 'zhōngjiān', 'in der Mitte', 'n'],
    ['对面', 'duìmiàn', 'gegenüber', 'n'],
    ['这儿', 'zhèr', 'hier', 's'],
    ['那儿', 'nàr', 'dort', 's'],
    ['哪儿', 'nǎr', 'wo', 's', 'Nǐ zài nǎr?', 'Wo bist du?', '你在哪儿？'],
    ['在', 'zài', 'sich befinden in', 'v'],
    ['远', 'yuǎn', 'weit', 'a'],
    ['近', 'jìn', 'nah', 'a'],
    ['到', 'dào', 'ankommen, bis', 'v'],
    ['路', 'lù', 'Weg, Straße', 'n'],
    ['拐', 'guǎi', 'abbiegen', 'v', 'Wǎng yòu guǎi.', 'Biegen Sie rechts ab.', '往右拐。']
  ],

  schule: [
    ['学校', 'xuéxiào', 'Schule', 'n'],
    ['学生', 'xuésheng', 'Schüler, Student', 'n'],
    ['老师', 'lǎoshī', 'Lehrer', 'n', 'Wáng lǎoshī jiāo Hànyǔ.', 'Lehrer Wang unterrichtet Chinesisch.', '王老师教汉语。'],
    ['同学', 'tóngxué', 'Mitschüler', 'n'],
    ['学习', 'xuéxí', 'lernen, studieren', 'v'],
    ['书', 'shū', 'Buch', 'n'],
    ['笔', 'bǐ', 'Stift', 'n'],
    ['纸', 'zhǐ', 'Papier', 'n'],
    ['教室', 'jiàoshì', 'Klassenzimmer', 'n'],
    ['上课', 'shàngkè', 'Unterricht haben', 'v'],
    ['课', 'kè', 'Unterrichtsstunde, Kurs', 'n'],
    ['问题', 'wèntí', 'Frage, Problem', 'n'],
    ['问', 'wèn', 'fragen', 'v'],
    ['回答', 'huídá', 'antworten', 'v'],
    ['写', 'xiě', 'schreiben', 'v'],
    ['读', 'dú', 'lesen, vorlesen', 'v'],
    ['懂', 'dǒng', 'verstehen', 'v', 'Wǒ bù dǒng.', 'Ich verstehe nicht.', '我不懂。'],
    ['知道', 'zhīdào', 'wissen', 'v'],
    ['大学', 'dàxué', 'Universität', 'n'],
    ['考试', 'kǎoshì', 'Prüfung', 'n']
  ],

  arbeit: [
    ['工作', 'gōngzuò', 'Arbeit, arbeiten', 'n', 'Tā zài yínháng gōngzuò.', 'Er arbeitet bei einer Bank.', '他在银行工作。'],
    ['公司', 'gōngsī', 'Firma', 'n'],
    ['老板', 'lǎobǎn', 'Chef', 'n'],
    ['经理', 'jīnglǐ', 'Manager, Abteilungsleiter', 'n'],
    ['同事', 'tóngshì', 'Kollege', 'n'],
    ['办公室', 'bàngōngshì', 'Büro', 'n'],
    ['开会', 'kāihuì', 'eine Besprechung haben', 'v'],
    ['忙', 'máng', 'beschäftigt', 'a', 'Zuìjìn wǒ hěn máng.', 'In letzter Zeit bin ich sehr beschäftigt.', '最近我很忙。'],
    ['做', 'zuò', 'machen, tun', 'v'],
    ['事情', 'shìqing', 'Angelegenheit', 'n'],
    ['帮忙', 'bāngmáng', 'helfen', 'v']
  ],

  freizeit: [
    ['玩儿', 'wánr', 'spielen, sich vergnügen', 'v'],
    ['看', 'kàn', 'sehen, ansehen', 'v', 'Wǒ xǐhuan kàn diànyǐng.', 'Ich sehe gern Filme.', '我喜欢看电影。'],
    ['电影', 'diànyǐng', 'Film', 'n'],
    ['音乐', 'yīnyuè', 'Musik', 'n'],
    ['听', 'tīng', 'hören, zuhören', 'v'],
    ['唱歌', 'chànggē', 'singen', 'v'],
    ['跳舞', 'tiàowǔ', 'tanzen', 'v'],
    ['旅游', 'lǚyóu', 'reisen', 'v'],
    ['照片', 'zhàopiàn', 'Foto', 'n'],
    ['爱好', 'àihào', 'Hobby', 'n'],
    ['休息', 'xiūxi', 'sich ausruhen', 'v'],
    ['喜欢', 'xǐhuan', 'mögen, gern haben', 'v'],
    ['有意思', 'yǒuyìsi', 'interessant', 'a']
  ],

  sport: [
    ['运动', 'yùndòng', 'Sport treiben, Bewegung', 'v'],
    ['跑步', 'pǎobù', 'joggen, laufen', 'v', 'Wǒ měi tiān zǎoshang pǎobù.', 'Ich jogge jeden Morgen.', '我每天早上跑步。'],
    ['游泳', 'yóuyǒng', 'schwimmen', 'v'],
    ['球', 'qiú', 'Ball', 'n'],
    ['足球', 'zúqiú', 'Fußball', 'n'],
    ['篮球', 'lánqiú', 'Basketball', 'n'],
    ['打', 'dǎ', 'schlagen, spielen (mit der Hand)', 'v'],
    ['踢', 'tī', 'treten, kicken', 'v'],
    ['比赛', 'bǐsài', 'Wettkampf, Spiel', 'n']
  ],

  natur: [
    ['山', 'shān', 'Berg', 'n'],
    ['河', 'hé', 'Fluss', 'n'],
    ['海', 'hǎi', 'Meer', 'n'],
    ['树', 'shù', 'Baum', 'n'],
    ['花', 'huā', 'Blume', 'n'],
    ['草', 'cǎo', 'Gras', 'n'],
    ['狗', 'gǒu', 'Hund', 'n'],
    ['猫', 'māo', 'Katze', 'n', 'Wǒ jiā yǒu yì zhī māo.', 'Ich habe eine Katze.', '我家有一只猫。'],
    ['鸟', 'niǎo', 'Vogel', 'n'],
    ['马', 'mǎ', 'Pferd', 'n'],
    ['月亮', 'yuèliang', 'Mond', 'n'],
    ['星星', 'xīngxing', 'Stern', 'n'],
    ['只', 'zhī', 'Zähleinheit für Tiere', 'p']
  ],

  technik: [
    ['电话', 'diànhuà', 'Telefon', 'n'],
    ['打电话', 'dǎ diànhuà', 'telefonieren', 'v', 'Wǒ gěi māma dǎ diànhuà.', 'Ich rufe meine Mutter an.', '我给妈妈打电话。'],
    ['手机', 'shǒujī', 'Handy', 'n'],
    ['电脑', 'diànnǎo', 'Computer', 'n'],
    ['上网', 'shàngwǎng', 'ins Internet gehen', 'v'],
    ['发', 'fā', 'senden, schicken', 'v'],
    ['号码', 'hàomǎ', 'Nummer', 'n'],
    ['网', 'wǎng', 'Netz, Internet', 'n']
  ],

  gefuehle: [
    ['快乐', 'kuàilè', 'fröhlich', 'a'],
    ['难过', 'nánguò', 'traurig, betrübt', 'a'],
    ['生气', 'shēngqì', 'wütend werden', 'v', 'Bié shēngqì.', 'Sei nicht böse.', '别生气。'],
    ['怕', 'pà', 'Angst haben vor', 'v'],
    ['笑', 'xiào', 'lachen, lächeln', 'v'],
    ['哭', 'kū', 'weinen', 'v'],
    ['心', 'xīn', 'Herz', 'n'],
    ['希望', 'xīwàng', 'hoffen', 'v'],
    ['觉得', 'juéde', 'finden, meinen', 'v', 'Wǒ juéde hěn hǎo.', 'Ich finde es sehr gut.', '我觉得很好。'],
    ['不好意思', 'bù hǎoyìsi', 'peinlich berührt sein', 'a']
  ],

  farben: [
    ['颜色', 'yánsè', 'Farbe', 'n'],
    ['红', 'hóng', 'rot', 'a'],
    ['蓝', 'lán', 'blau', 'a'],
    ['黄', 'huáng', 'gelb', 'a'],
    ['绿', 'lǜ', 'grün', 'a'],
    ['黑', 'hēi', 'schwarz', 'a'],
    ['白', 'bái', 'weiß', 'a'],
    ['灰', 'huī', 'grau', 'a'],
    ['长', 'cháng', 'lang', 'a'],
    ['短', 'duǎn', 'kurz', 'a'],
    ['高', 'gāo', 'hoch, groß (Person)', 'a'],
    ['圆', 'yuán', 'rund', 'a']
  ],

  stadt: [
    ['城市', 'chéngshì', 'Stadt', 'n'],
    ['银行', 'yínháng', 'Bank', 'n'],
    ['邮局', 'yóujú', 'Post', 'n'],
    ['公园', 'gōngyuán', 'Park', 'n'],
    ['饭店', 'fàndiàn', 'Hotel, Restaurant', 'n'],
    ['路口', 'lùkǒu', 'Kreuzung', 'n'],
    ['地方', 'dìfang', 'Ort, Platz', 'n'],
    ['国家', 'guójiā', 'Land, Staat', 'n'],
    ['北京', 'Běijīng', 'Peking', 'n'],
    ['地图', 'dìtú', 'Landkarte', 'n']
  ]

});
