/* Pinyin-Trainer – Wortschatz B2
 * Format: [hanzi, pinyin, deutsch, wortart, beispielPinyin?, beispielDe?, beispielHanzi?]
 */
VokabelDaten.add('B2', {

  begruessung: [
    ['寒暄', 'hánxuān', 'Höflichkeitsfloskeln austauschen', 'v'],
    ['委婉', 'wěiwǎn', 'behutsam, indirekt formuliert', 'a', 'Tā wěiwǎn de jùjué le wǒ.', 'Er hat mich behutsam abgelehnt.', '他委婉地拒绝了我。'],
    ['含蓄', 'hánxù', 'zurückhaltend, andeutend', 'a'],
    ['直率', 'zhíshuài', 'freiheraus, direkt', 'a'],
    ['分寸', 'fēncùn', 'rechtes Maß, Fingerspitzengefühl', 'n'],
    ['场合', 'chǎnghé', 'Anlass, Situation', 'n'],
    ['得体', 'détǐ', 'angemessen, taktvoll', 'a'],
    ['称赞', 'chēngzàn', 'loben', 'v'],
    ['谦虚', 'qiānxū', 'bescheiden', 'a'],
    ['冒昧', 'màomèi', 'sich erdreisten (höfliche Floskel)', 'a'],
    ['人脉', 'rénmài', 'Beziehungsnetz, Kontakte', 'n'],
    ['面子', 'miànzi', 'Gesicht, Ansehen', 'n', 'Zhè yàng zuò huì ràng tā méi miànzi.', 'So zu handeln würde ihn das Gesicht verlieren lassen.', '这样做会让他没面子。']
  ],

  zahlen: [
    ['比率', 'bǐlǜ', 'Quote, Rate', 'n'],
    ['增长', 'zēngzhǎng', 'Zuwachs, wachsen', 'v', 'Jīngjì zēngzhǎng fàngmàn le.', 'Das Wirtschaftswachstum hat sich verlangsamt.', '经济增长放慢了。'],
    ['下降', 'xiàjiàng', 'sinken, zurückgehen', 'v'],
    ['上升', 'shàngshēng', 'steigen', 'v'],
    ['保持不变', 'bǎochí búbiàn', 'unverändert bleiben', 'v'],
    ['占', 'zhàn', 'ausmachen, einnehmen (Anteil)', 'v'],
    ['数量', 'shùliàng', 'Menge, Anzahl', 'n'],
    ['程度', 'chéngdù', 'Grad, Ausmaß', 'n'],
    ['阶段', 'jiēduàn', 'Phase, Etappe', 'n'],
    ['长期', 'chángqī', 'langfristig', 'a'],
    ['短期', 'duǎnqī', 'kurzfristig', 'a'],
    ['截止', 'jiézhǐ', 'enden am, Stichtag', 'v']
  ],

  familie: [
    ['血缘', 'xuèyuán', 'Blutsverwandtschaft', 'n'],
    ['家族', 'jiāzú', 'Sippe, Clan', 'n'],
    ['继承', 'jìchéng', 'erben, fortführen', 'v'],
    ['抚养', 'fǔyǎng', 'großziehen, unterhalten', 'v'],
    ['赡养', 'shànyǎng', 'für Angehörige sorgen', 'v'],
    ['孝顺', 'xiàoshùn', 'kindliche Ehrerbietung zeigen', 'a', 'Tā shì ge hěn xiàoshùn de érzi.', 'Er ist ein sehr pflichtbewusster Sohn.', '他是个很孝顺的儿子。'],
    ['独立', 'dúlì', 'selbstständig, unabhängig', 'a'],
    ['依赖', 'yīlài', 'abhängig sein von', 'v'],
    ['单亲', 'dānqīn', 'alleinerziehend', 'a'],
    ['老龄化', 'lǎolínghuà', 'Überalterung', 'n'],
    ['婚姻', 'hūnyīn', 'Ehe', 'n'],
    ['伴侣', 'bànlǚ', 'Lebenspartner', 'n'],
    ['矛盾', 'máodùn', 'Widerspruch, Konflikt', 'n'],
    ['和睦', 'hémù', 'harmonisch, einträchtig', 'a'],
    ['隔阂', 'géhé', 'Entfremdung, Kluft', 'n'],
    ['观念', 'guānniàn', 'Vorstellung, Denkweise', 'n']
  ],

  essen: [
    ['饮食', 'yǐnshí', 'Ernährung, Kost', 'n', 'Jiànkāng de yǐnshí hěn zhòngyào.', 'Eine gesunde Ernährung ist sehr wichtig.', '健康的饮食很重要。'],
    ['菜系', 'càixì', 'Küchenstil, Regionalküche', 'n'],
    ['风味', 'fēngwèi', 'lokaltypischer Geschmack', 'n'],
    ['调料', 'tiáoliào', 'Gewürz, Würzmittel', 'n'],
    ['添加剂', 'tiānjiājì', 'Zusatzstoff', 'n'],
    ['食品安全', 'shípǐn ānquán', 'Lebensmittelsicherheit', 'n'],
    ['卫生', 'wèishēng', 'Hygiene, hygienisch', 'n'],
    ['保质期', 'bǎozhìqī', 'Mindesthaltbarkeitsdatum', 'n'],
    ['有机', 'yǒujī', 'Bio-, organisch', 'a'],
    ['摄入', 'shèrù', 'aufnehmen (Nährstoffe)', 'v'],
    ['热量', 'rèliàng', 'Kalorien', 'n'],
    ['节制', 'jiézhì', 'maßhalten', 'v'],
    ['讲究', 'jiǎngjiu', 'Wert legen auf, anspruchsvoll', 'v'],
    ['款待', 'kuǎndài', 'bewirten', 'v']
  ],

  einkaufen: [
    ['理财', 'lǐcái', 'Vermögen verwalten', 'v'],
    ['储蓄', 'chǔxù', 'Ersparnisse, sparen', 'n'],
    ['贷款', 'dàikuǎn', 'Kredit, einen Kredit aufnehmen', 'n', 'Tā shēnqǐng le zhùfáng dàikuǎn.', 'Er hat einen Immobilienkredit beantragt.', '他申请了住房贷款。'],
    ['利息', 'lìxī', 'Zinsen', 'n'],
    ['汇率', 'huìlǜ', 'Wechselkurs', 'n'],
    ['通货膨胀', 'tōnghuò péngzhàng', 'Inflation', 'n'],
    ['退款', 'tuìkuǎn', 'Rückerstattung', 'n'],
    ['保修', 'bǎoxiū', 'Garantie', 'n'],
    ['维权', 'wéiquán', 'seine Rechte wahrnehmen', 'v'],
    ['理性', 'lǐxìng', 'rational, vernünftig', 'a'],
    ['冲动', 'chōngdòng', 'impulsiv, Impuls', 'a'],
    ['奢侈', 'shēchǐ', 'luxuriös, verschwenderisch', 'a'],
    ['性价比', 'xìngjiàbǐ', 'Preis-Leistungs-Verhältnis', 'n'],
    ['囤积', 'túnjī', 'horten', 'v']
  ],

  wohnen: [
    ['房价', 'fángjià', 'Immobilienpreis', 'n', 'Dà chéngshì de fángjià tài gāo le.', 'Die Immobilienpreise in Großstädten sind zu hoch.', '大城市的房价太高了。'],
    ['产权', 'chǎnquán', 'Eigentumsrecht', 'n'],
    ['物业', 'wùyè', 'Hausverwaltung', 'n'],
    ['居住', 'jūzhù', 'wohnen, ansässig sein', 'v'],
    ['条件', 'tiáojiàn', 'Bedingung, Voraussetzung', 'n'],
    ['隔音', 'géyīn', 'schalldicht', 'a'],
    ['采光', 'cǎiguāng', 'Lichtverhältnisse', 'n'],
    ['朝向', 'cháoxiàng', 'Ausrichtung (Himmelsrichtung)', 'n'],
    ['节能', 'jiénéng', 'energiesparend', 'a'],
    ['翻新', 'fānxīn', 'sanieren', 'v'],
    ['家电', 'jiādiàn', 'Haushaltsgeräte', 'n'],
    ['设计', 'shèjì', 'Gestaltung, entwerfen', 'n'],
    ['空间', 'kōngjiān', 'Raum, Platz', 'n'],
    ['邻里', 'línlǐ', 'Nachbarschaft', 'n']
  ],

  koerper: [
    ['免疫', 'miǎnyì', 'Immunität, immun', 'n'],
    ['慢性病', 'mànxìngbìng', 'chronische Krankheit', 'n'],
    ['传染', 'chuánrǎn', 'ansteckend sein, übertragen', 'v', 'Zhè zhǒng bìng huì chuánrǎn.', 'Diese Krankheit ist ansteckend.', '这种病会传染。'],
    ['诊断', 'zhěnduàn', 'Diagnose, diagnostizieren', 'n'],
    ['处方', 'chǔfāng', 'Rezept (ärztlich)', 'n'],
    ['副作用', 'fùzuòyòng', 'Nebenwirkung', 'n'],
    ['康复', 'kāngfù', 'Genesung, genesen', 'v'],
    ['心理', 'xīnlǐ', 'Psyche, psychisch', 'n'],
    ['焦虑', 'jiāolǜ', 'Angstzustand, ängstlich', 'n'],
    ['抑郁', 'yìyù', 'depressiv, Depression', 'a'],
    ['失眠', 'shīmián', 'Schlaflosigkeit', 'n'],
    ['疲劳', 'píláo', 'Erschöpfung', 'n'],
    ['缓解', 'huǎnjiě', 'lindern', 'v'],
    ['作息', 'zuòxī', 'Tagesrhythmus', 'n'],
    ['医疗', 'yīliáo', 'medizinische Versorgung', 'n'],
    ['公共卫生', 'gōnggòng wèishēng', 'öffentliche Gesundheit', 'n'],
    ['养生', 'yǎngshēng', 'Gesundheitspflege', 'n'],
    ['寿命', 'shòumìng', 'Lebenserwartung', 'n']
  ],

  kleidung: [
    ['服装', 'fúzhuāng', 'Bekleidung (Branche)', 'n'],
    ['面料', 'miànliào', 'Stoff, Material', 'n'],
    ['剪裁', 'jiǎncái', 'Schnitt (Kleidung)', 'n'],
    ['品位', 'pǐnwèi', 'Geschmack, Stilgefühl', 'n', 'Tā chuānyī hěn yǒu pǐnwèi.', 'Sie kleidet sich sehr geschmackvoll.', '她穿衣很有品位。'],
    ['潮流', 'cháoliú', 'Trend, Strömung', 'n'],
    ['定制', 'dìngzhì', 'maßanfertigen', 'v'],
    ['环保材料', 'huánbǎo cáiliào', 'umweltfreundliches Material', 'n'],
    ['快时尚', 'kuài shíshàng', 'Fast Fashion', 'n'],
    ['款式', 'kuǎnshì', 'Modell, Machart', 'n'],
    ['整洁', 'zhěngjié', 'gepflegt, sauber', 'a']
  ],

  wetter: [
    ['全球变暖', 'quánqiú biànnuǎn', 'globale Erwärmung', 'n'],
    ['温室效应', 'wēnshì xiàoyìng', 'Treibhauseffekt', 'n'],
    ['排放', 'páifàng', 'Emission, ausstoßen', 'v', 'Èryǎnghuàtàn páifàng bìxū jiǎnshǎo.', 'Die CO2-Emissionen müssen verringert werden.', '二氧化碳排放必须减少。'],
    ['极端', 'jíduān', 'extrem', 'a'],
    ['气象', 'qìxiàng', 'Meteorologie, Wetterlage', 'n'],
    ['监测', 'jiāncè', 'überwachen, messen', 'v'],
    ['预警', 'yùjǐng', 'Frühwarnung', 'n'],
    ['融化', 'rónghuà', 'schmelzen', 'v'],
    ['冰川', 'bīngchuān', 'Gletscher', 'n'],
    ['海平面', 'hǎipíngmiàn', 'Meeresspiegel', 'n'],
    ['适应', 'shìyìng', 'sich anpassen', 'v'],
    ['应对', 'yìngduì', 'bewältigen, reagieren auf', 'v']
  ],

  verkehr: [
    ['基础设施', 'jīchǔ shèshī', 'Infrastruktur', 'n'],
    ['拥堵', 'yōngdǔ', 'Verkehrsstau', 'n', 'Shàngxiàbān gāofēng yōngdǔ yánzhòng.', 'Zur Hauptverkehrszeit ist der Stau schlimm.', '上下班高峰拥堵严重。'],
    ['高峰期', 'gāofēngqī', 'Stoßzeit', 'n'],
    ['限行', 'xiànxíng', 'Fahrverbot nach Kennzeichen', 'v'],
    ['新能源车', 'xīn néngyuán chē', 'Fahrzeug mit alternativem Antrieb', 'n'],
    ['充电桩', 'chōngdiànzhuāng', 'Ladesäule', 'n'],
    ['自动驾驶', 'zìdòng jiàshǐ', 'autonomes Fahren', 'n'],
    ['共享', 'gòngxiǎng', 'geteilt nutzen, Sharing', 'v'],
    ['里程', 'lǐchéng', 'Fahrstrecke, Kilometerstand', 'n'],
    ['罚款', 'fákuǎn', 'Bußgeld', 'n'],
    ['违章', 'wéizhāng', 'gegen Vorschriften verstoßen', 'v'],
    ['疏导', 'shūdǎo', 'Verkehr lenken, entzerren', 'v'],
    ['航线', 'hángxiàn', 'Flug- oder Schifffahrtsroute', 'n'],
    ['物流', 'wùliú', 'Logistik', 'n']
  ],

  richtungen: [
    ['方位', 'fāngwèi', 'Himmelsrichtung, Position', 'n'],
    ['坐标', 'zuòbiāo', 'Koordinate', 'n'],
    ['定位', 'dìngwèi', 'Ortung, verorten', 'v'],
    ['导航', 'dǎoháng', 'Navigation', 'n', 'Gēnzhe dǎoháng zǒu jiù bú huì mílù.', 'Wenn du dem Navi folgst, verläufst du dich nicht.', '跟着导航走就不会迷路。'],
    ['范围', 'fànwéi', 'Bereich, Umfang', 'n'],
    ['边界', 'biānjiè', 'Grenze', 'n'],
    ['偏', 'piān', 'abweichend, schief', 'a'],
    ['遥远', 'yáoyuǎn', 'weit entfernt', 'a'],
    ['交界', 'jiāojiè', 'aneinandergrenzen', 'v'],
    ['腹地', 'fùdì', 'Hinterland', 'n']
  ],

  schule: [
    ['学术', 'xuéshù', 'wissenschaftlich, Wissenschaft', 'n'],
    ['研究', 'yánjiū', 'Forschung, erforschen', 'n'],
    ['分析', 'fēnxī', 'analysieren, Analyse', 'v'],
    ['论证', 'lùnzhèng', 'argumentieren, beweisen', 'v'],
    ['引用', 'yǐnyòng', 'zitieren', 'v'],
    ['文献', 'wénxiàn', 'Fachliteratur, Quellen', 'n'],
    ['导师', 'dǎoshī', 'Betreuer, Doktorvater', 'n'],
    ['学位', 'xuéwèi', 'akademischer Grad', 'n'],
    ['硕士', 'shuòshì', 'Master', 'n'],
    ['博士', 'bóshì', 'Doktor, Promotion', 'n'],
    ['竞争激烈', 'jìngzhēng jīliè', 'harter Wettbewerb', 'a'],
    ['应试教育', 'yìngshì jiàoyù', 'prüfungsorientierte Bildung', 'n', 'Yìngshì jiàoyù shòudào le hěn duō pīpíng.', 'Die prüfungsorientierte Bildung ist stark kritisiert worden.', '应试教育受到了很多批评。'],
    ['素质', 'sùzhì', 'Qualität, Bildungsniveau (einer Person)', 'n'],
    ['终身学习', 'zhōngshēn xuéxí', 'lebenslanges Lernen', 'n'],
    ['在线课程', 'zàixiàn kèchéng', 'Onlinekurs', 'n'],
    ['自学', 'zìxué', 'im Selbststudium lernen', 'v'],
    ['思维', 'sīwéi', 'Denken, Denkweise', 'n'],
    ['批判', 'pīpàn', 'kritisch hinterfragen', 'v'],
    ['创新', 'chuàngxīn', 'Innovation, erneuern', 'n'],
    ['启发', 'qǐfā', 'anregen, Anstoß geben', 'v']
  ],

  arbeit: [
    ['行业', 'hángyè', 'Branche', 'n'],
    ['岗位', 'gǎngwèi', 'Arbeitsplatz, Posten', 'n'],
    ['晋升', 'jìnshēng', 'Beförderung', 'n'],
    ['绩效', 'jìxiào', 'Leistung, Performance', 'n', 'Gōngsī àn jìxiào fā jiǎngjīn.', 'Die Firma zahlt Boni nach Leistung.', '公司按绩效发奖金。'],
    ['考核', 'kǎohé', 'Beurteilung, bewerten', 'n'],
    ['激励', 'jīlì', 'Anreiz schaffen, motivieren', 'v'],
    ['管理', 'guǎnlǐ', 'Management, verwalten', 'n'],
    ['领导', 'lǐngdǎo', 'Führung, Vorgesetzter', 'n'],
    ['执行', 'zhíxíng', 'ausführen, umsetzen', 'v'],
    ['流程', 'liúchéng', 'Arbeitsablauf, Prozess', 'n'],
    ['协调', 'xiétiáo', 'koordinieren, abstimmen', 'v'],
    ['分工', 'fēngōng', 'Arbeitsteilung', 'n'],
    ['职场', 'zhíchǎng', 'Berufswelt', 'n'],
    ['跳槽', 'tiàocáo', 'den Arbeitgeber wechseln', 'v'],
    ['劳动合同', 'láodòng hétong', 'Arbeitsvertrag', 'n'],
    ['权益', 'quányì', 'Rechte und Interessen', 'n'],
    ['工会', 'gōnghuì', 'Gewerkschaft', 'n'],
    ['远程办公', 'yuǎnchéng bàngōng', 'Homeoffice, Fernarbeit', 'n'],
    ['工作与生活平衡', 'gōngzuò yǔ shēnghuó pínghéng', 'Work-Life-Balance', 'n'],
    ['过劳', 'guòláo', 'Überarbeitung', 'n'],
    ['职业发展', 'zhíyè fāzhǎn', 'berufliche Entwicklung', 'n'],
    ['人才', 'réncái', 'Fachkraft, Talent', 'n']
  ],

  freizeit: [
    ['艺术', 'yìshù', 'Kunst', 'n'],
    ['审美', 'shěnměi', 'ästhetisches Empfinden', 'n'],
    ['风景', 'fēngjǐng', 'Landschaft, Aussicht', 'n'],
    ['旅行社', 'lǚxíngshè', 'Reisebüro', 'n'],
    ['自由行', 'zìyóuxíng', 'Individualreise', 'n'],
    ['背包客', 'bèibāokè', 'Rucksackreisender', 'n'],
    ['深度游', 'shēndùyóu', 'Reise mit kulturellem Tiefgang', 'n'],
    ['沉浸', 'chénjìn', 'eintauchen, versinken in', 'v', 'Tā chénjìn zài yīnyuè lǐ.', 'Sie versinkt in der Musik.', '她沉浸在音乐里。'],
    ['爱不释手', 'ài bú shì shǒu', 'etwas nicht aus der Hand legen können', 's'],
    ['入迷', 'rùmí', 'gefesselt sein', 'v'],
    ['娱乐圈', 'yúlèquān', 'Unterhaltungsbranche', 'n'],
    ['明星', 'míngxīng', 'Star, Prominenter', 'n'],
    ['粉丝', 'fěnsī', 'Fan', 'n'],
    ['作品', 'zuòpǐn', 'Werk', 'n'],
    ['题材', 'tícái', 'Sujet, Thema (Kunst)', 'n'],
    ['欣赏', 'xīnshǎng', 'würdigen, genießen', 'v']
  ],

  sport: [
    ['体能', 'tǐnéng', 'Kondition', 'n'],
    ['耐力', 'nàilì', 'Ausdauer', 'n'],
    ['爆发力', 'bàofālì', 'Schnellkraft', 'n'],
    ['战术', 'zhànshù', 'Taktik', 'n'],
    ['配合', 'pèihé', 'zusammenspielen', 'v', 'Duìyuán zhī jiān pèihé de hěn hǎo.', 'Die Teamkollegen spielen sehr gut zusammen.', '队员之间配合得很好。'],
    ['兴奋剂', 'xīngfènjì', 'Dopingmittel', 'n'],
    ['公平', 'gōngpíng', 'fair, gerecht', 'a'],
    ['业余爱好者', 'yèyú àihàozhě', 'Amateur', 'n'],
    ['职业化', 'zhíyèhuà', 'Professionalisierung', 'n'],
    ['赛季', 'sàijì', 'Saison', 'n'],
    ['伤病', 'shāngbìng', 'Verletzung', 'n'],
    ['全民健身', 'quánmín jiànshēn', 'Breitensport', 'n']
  ],

  natur: [
    ['生物', 'shēngwù', 'Lebewesen, Biologie', 'n'],
    ['多样性', 'duōyàngxìng', 'Vielfalt, Diversität', 'n'],
    ['栖息地', 'qīxīdì', 'Lebensraum', 'n'],
    ['灭绝', 'mièjué', 'aussterben', 'v', 'Xǔduō wùzhǒng miànlín mièjué.', 'Viele Arten stehen vor dem Aussterben.', '许多物种面临灭绝。'],
    ['破坏', 'pòhuài', 'zerstören', 'v'],
    ['退化', 'tuìhuà', 'degradieren, verfallen', 'v'],
    ['植被', 'zhíbèi', 'Vegetation', 'n'],
    ['森林砍伐', 'sēnlín kǎnfá', 'Abholzung', 'n'],
    ['可持续', 'kě chíxù', 'nachhaltig', 'a'],
    ['循环', 'xúnhuán', 'Kreislauf, zirkulieren', 'n'],
    ['废物', 'fèiwù', 'Abfall', 'n'],
    ['处置', 'chǔzhì', 'entsorgen, behandeln', 'v'],
    ['碳中和', 'tàn zhōnghé', 'Klimaneutralität', 'n'],
    ['风能', 'fēngnéng', 'Windenergie', 'n'],
    ['核能', 'hénéng', 'Kernenergie', 'n'],
    ['意识', 'yìshí', 'Bewusstsein', 'n'],
    ['倡导', 'chàngdǎo', 'sich einsetzen für', 'v'],
    ['自然保护区', 'zìrán bǎohùqū', 'Naturschutzgebiet', 'n'],
    ['生态平衡', 'shēngtài pínghéng', 'ökologisches Gleichgewicht', 'n'],
    ['污染源', 'wūrǎnyuán', 'Schadstoffquelle', 'n']
  ],

  technik: [
    ['数字化', 'shùzìhuà', 'Digitalisierung', 'n'],
    ['算法', 'suànfǎ', 'Algorithmus', 'n'],
    ['大数据', 'dà shùjù', 'Big Data', 'n'],
    ['云计算', 'yún jìsuàn', 'Cloud Computing', 'n'],
    ['芯片', 'xīnpiàn', 'Chip', 'n'],
    ['研发', 'yánfā', 'Forschung und Entwicklung', 'n', 'Gōngsī měi nián tóurù dàliàng yánfā fèiyòng.', 'Die Firma investiert jährlich viel in F&E.', '公司每年投入大量研发费用。'],
    ['专利', 'zhuānlì', 'Patent', 'n'],
    ['平台', 'píngtái', 'Plattform', 'n'],
    ['用户', 'yònghù', 'Nutzer', 'n'],
    ['界面', 'jièmiàn', 'Benutzeroberfläche', 'n'],
    ['智能', 'zhìnéng', 'intelligent, smart', 'a'],
    ['自动化', 'zìdònghuà', 'Automatisierung', 'n'],
    ['取代', 'qǔdài', 'ersetzen, verdrängen', 'v'],
    ['信息', 'xìnxī', 'Information', 'n'],
    ['泄露', 'xièlòu', 'durchsickern, preisgeben', 'v'],
    ['监控', 'jiānkòng', 'überwachen, Überwachung', 'v'],
    ['网络安全', 'wǎngluò ānquán', 'Cybersicherheit', 'n'],
    ['依赖症', 'yīlàizhèng', 'Abhängigkeit, Sucht', 'n'],
    ['沉迷', 'chénmí', 'süchtig verfallen sein', 'v'],
    ['屏幕时间', 'píngmù shíjiān', 'Bildschirmzeit', 'n'],
    ['虚假信息', 'xūjiǎ xìnxī', 'Falschinformation', 'n'],
    ['伦理', 'lúnlǐ', 'Ethik', 'n'],
    ['规范', 'guīfàn', 'Norm, regulieren', 'n'],
    ['普及', 'pǔjí', 'sich verbreiten, verbreiten', 'v']
  ],

  gefuehle: [
    ['心态', 'xīntài', 'innere Haltung, Mentalität', 'n', 'Bǎochí liánghǎo de xīntài hěn zhòngyào.', 'Eine gute innere Haltung zu bewahren ist wichtig.', '保持良好的心态很重要。'],
    ['情感', 'qínggǎn', 'Gefühl, Emotion', 'n'],
    ['内向', 'nèixiàng', 'introvertiert', 'a'],
    ['外向', 'wàixiàng', 'extrovertiert', 'a'],
    ['敏感', 'mǐngǎn', 'empfindlich, sensibel', 'a'],
    ['迟钝', 'chídùn', 'begriffsstutzig, träge', 'a'],
    ['冷静', 'lěngjìng', 'besonnen, ruhig', 'a'],
    ['冲突', 'chōngtū', 'Konflikt', 'n'],
    ['包容', 'bāoróng', 'tolerieren, einschließen', 'v'],
    ['理解', 'lǐjiě', 'verstehen, Verständnis', 'v'],
    ['体谅', 'tǐliàng', 'Nachsicht üben', 'v'],
    ['埋怨', 'mányuàn', 'sich beklagen über', 'v'],
    ['抱怨', 'bàoyuàn', 'sich beschweren', 'v'],
    ['自卑', 'zìbēi', 'Minderwertigkeitsgefühle haben', 'a'],
    ['虚荣', 'xūróng', 'eitel', 'a'],
    ['真诚', 'zhēnchéng', 'aufrichtig', 'a'],
    ['虚伪', 'xūwěi', 'heuchlerisch', 'a'],
    ['成熟', 'chéngshú', 'reif', 'a'],
    ['幼稚', 'yòuzhì', 'kindisch', 'a'],
    ['毅力', 'yìlì', 'Willenskraft', 'n'],
    ['克服', 'kèfú', 'überwinden', 'v'],
    ['承受', 'chéngshòu', 'ertragen, aushalten', 'v'],
    ['释放', 'shìfàng', 'freisetzen, abbauen', 'v'],
    ['依恋', 'yīliàn', 'sich anhänglich fühlen', 'v']
  ],

  farben: [
    ['色调', 'sèdiào', 'Farbton, Stimmung', 'n'],
    ['配色', 'pèisè', 'Farbabstimmung', 'n'],
    ['视觉', 'shìjué', 'Sehsinn, visuell', 'n'],
    ['立体', 'lìtǐ', 'dreidimensional', 'a'],
    ['层次', 'céngcì', 'Abstufung, Ebene', 'n'],
    ['轮廓', 'lúnkuò', 'Umriss', 'n'],
    ['纹理', 'wénlǐ', 'Maserung, Textur', 'n'],
    ['构图', 'gòutú', 'Bildaufbau', 'n']
  ],

  stadt: [
    ['城市化', 'chéngshìhuà', 'Urbanisierung', 'n', 'Chéngshìhuà dàilái le xǔduō wèntí.', 'Die Urbanisierung hat viele Probleme mit sich gebracht.', '城市化带来了许多问题。'],
    ['户口', 'hùkǒu', 'Haushaltsregistrierung', 'n'],
    ['流动人口', 'liúdòng rénkǒu', 'Wanderbevölkerung', 'n'],
    ['基层', 'jīcéng', 'Basisebene, lokale Ebene', 'n'],
    ['行政', 'xíngzhèng', 'Verwaltung, administrativ', 'n'],
    ['政策', 'zhèngcè', 'Politik, Richtlinie', 'n'],
    ['法规', 'fǎguī', 'Vorschrift, Verordnung', 'n'],
    ['执法', 'zhífǎ', 'Recht durchsetzen', 'v'],
    ['公共服务', 'gōnggòng fúwù', 'öffentliche Dienstleistung', 'n'],
    ['配套', 'pèitào', 'ergänzende Infrastruktur', 'n'],
    ['改造', 'gǎizào', 'umgestalten, sanieren', 'v'],
    ['拆迁', 'chāiqiān', 'Abriss und Umsiedlung', 'n'],
    ['历史街区', 'lìshǐ jiēqū', 'historisches Viertel', 'n'],
    ['地标', 'dìbiāo', 'Wahrzeichen', 'n'],
    ['宜居', 'yíjū', 'lebenswert', 'a'],
    ['贫富差距', 'pínfù chājù', 'Kluft zwischen Arm und Reich', 'n'],
    ['公共交通', 'gōnggòng jiāotōng', 'öffentlicher Nahverkehr', 'n'],
    ['绿化', 'lǜhuà', 'Begrünung', 'n'],
    ['区域', 'qūyù', 'Region, Zone', 'n'],
    ['协调发展', 'xiétiáo fāzhǎn', 'ausgewogene Entwicklung', 'n']
  ],

  feste: [
    ['文化', 'wénhuà', 'Kultur', 'n'],
    ['传承', 'chuánchéng', 'weitergeben (Tradition)', 'v', 'Zhè xiàng shǒuyì yǐjīng chuánchéng le jǐ bǎi nián.', 'Dieses Handwerk wird seit Jahrhunderten weitergegeben.', '这项手艺已经传承了几百年。'],
    ['遗产', 'yíchǎn', 'Erbe, Erbgut', 'n'],
    ['非物质文化遗产', 'fēiwùzhì wénhuà yíchǎn', 'immaterielles Kulturerbe', 'n'],
    ['仪式', 'yíshì', 'Zeremonie', 'n'],
    ['禁忌', 'jìnjì', 'Tabu', 'n'],
    ['寓意', 'yùyì', 'übertragene Bedeutung', 'n'],
    ['吉祥', 'jíxiáng', 'glückverheißend', 'a'],
    ['团圆', 'tuányuán', 'Wiedervereinigung der Familie', 'n'],
    ['祭祀', 'jìsì', 'Opferzeremonie abhalten', 'v'],
    ['民俗', 'mínsú', 'Volksbrauchtum', 'n'],
    ['起源', 'qǐyuán', 'Ursprung, entspringen', 'n'],
    ['演变', 'yǎnbiàn', 'sich wandeln', 'v'],
    ['融合', 'rónghé', 'verschmelzen', 'v']
  ],

  meinung: [
    ['立场', 'lìchǎng', 'Position, Standpunkt', 'n'],
    ['论点', 'lùndiǎn', 'These, Argument', 'n'],
    ['论据', 'lùnjù', 'Beleg, Beweisgrund', 'n'],
    ['依据', 'yījù', 'Grundlage, sich stützen auf', 'n'],
    ['前提', 'qiántí', 'Voraussetzung', 'n'],
    ['逻辑', 'luójí', 'Logik', 'n'],
    ['客观', 'kèguān', 'objektiv', 'a'],
    ['主观', 'zhǔguān', 'subjektiv', 'a'],
    ['片面', 'piànmiàn', 'einseitig', 'a', 'Zhè zhǒng kànfǎ tài piànmiàn le.', 'Diese Sichtweise ist zu einseitig.', '这种看法太片面了。'],
    ['全面', 'quánmiàn', 'umfassend', 'a'],
    ['深入', 'shēnrù', 'tiefgehend, vertiefen', 'a'],
    ['反驳', 'fǎnbó', 'widerlegen', 'v'],
    ['质疑', 'zhìyí', 'infrage stellen', 'v'],
    ['批评', 'pīpíng', 'kritisieren', 'v'],
    ['辩论', 'biànlùn', 'debattieren', 'v'],
    ['立足', 'lìzú', 'ausgehen von, fußen auf', 'v'],
    ['归根结底', 'guīgēn jiédǐ', 'letztendlich, im Kern', 's'],
    ['一方面', 'yì fāngmiàn', 'einerseits', 's'],
    ['另一方面', 'lìng yì fāngmiàn', 'andererseits', 's'],
    ['相比之下', 'xiāngbǐ zhī xià', 'im Vergleich dazu', 's'],
    ['与其', 'yǔqí', 'anstatt, lieber als', 's'],
    ['宁可', 'nìngkě', 'lieber (etwas in Kauf nehmen)', 'd'],
    ['未必', 'wèibì', 'nicht unbedingt', 'd'],
    ['显然', 'xiǎnrán', 'offensichtlich', 'd'],
    ['据说', 'jùshuō', 'es heißt, angeblich', 'd'],
    ['无论如何', 'wúlùn rúhé', 'auf jeden Fall', 's'],
    ['值得', 'zhídé', 'wert sein', 'v'],
    ['忽视', 'hūshì', 'übersehen, vernachlässigen', 'v'],
    ['重视', 'zhòngshì', 'hohen Wert legen auf', 'v'],
    ['妥当', 'tuǒdàng', 'angemessen, sachgerecht', 'a']
  ],

  nachrichten: [
    ['时事', 'shíshì', 'Zeitgeschehen', 'n'],
    ['头条', 'tóutiáo', 'Schlagzeile', 'n'],
    ['舆论', 'yúlùn', 'öffentliche Meinung', 'n', 'Zhè jiàn shì yǐnqǐ le yúlùn guānzhù.', 'Diese Sache hat öffentliche Aufmerksamkeit erregt.', '这件事引起了舆论关注。'],
    ['引起', 'yǐnqǐ', 'hervorrufen, auslösen', 'v'],
    ['争议', 'zhēngyì', 'Kontroverse', 'n'],
    ['披露', 'pīlù', 'enthüllen, aufdecken', 'v'],
    ['真相', 'zhēnxiàng', 'Wahrheit, wahrer Sachverhalt', 'n'],
    ['谣言', 'yáoyán', 'Gerücht', 'n'],
    ['辟谣', 'pìyáo', 'ein Gerücht richtigstellen', 'v'],
    ['官方', 'guānfāng', 'offiziell, amtlich', 'a'],
    ['发言人', 'fāyánrén', 'Sprecher', 'n'],
    ['声明', 'shēngmíng', 'Erklärung, erklären', 'n'],
    ['政治', 'zhèngzhì', 'Politik', 'n'],
    ['选举', 'xuǎnjǔ', 'Wahl, wählen', 'n'],
    ['法律', 'fǎlǜ', 'Gesetz', 'n'],
    ['权利', 'quánlì', 'Recht, Anspruch', 'n'],
    ['义务', 'yìwù', 'Pflicht', 'n'],
    ['平等', 'píngděng', 'Gleichheit, gleichberechtigt', 'a'],
    ['歧视', 'qíshì', 'Diskriminierung, diskriminieren', 'n'],
    ['福利制度', 'fúlì zhìdù', 'Sozialsystem', 'n'],
    ['贫困', 'pínkùn', 'Armut, arm', 'a'],
    ['慈善', 'císhàn', 'Wohltätigkeit', 'n'],
    ['志愿者', 'zhìyuànzhě', 'Freiwilliger', 'n'],
    ['公益', 'gōngyì', 'Gemeinwohl', 'n'],
    ['移民', 'yímín', 'Migration, Migrant', 'n'],
    ['难民', 'nànmín', 'Flüchtling', 'n'],
    ['国际', 'guójì', 'international', 'a'],
    ['冲击', 'chōngjī', 'Erschütterung, treffen', 'n'],
    ['局势', 'júshì', 'Lage, Situation', 'n'],
    ['危机', 'wēijī', 'Krise', 'n'],
    ['应急', 'yìngjí', 'Notfall-, Krisenreaktion', 'a'],
    ['措施', 'cuòshī', 'Maßnahme', 'n', 'Zhèngfǔ cǎiqǔ le yìxiē cuòshī.', 'Die Regierung hat einige Maßnahmen ergriffen.', '政府采取了一些措施。'],
    ['采取', 'cǎiqǔ', 'ergreifen (Maßnahmen)', 'v'],
    ['实施', 'shíshī', 'umsetzen, in Kraft setzen', 'v'],
    ['效果', 'xiàoguǒ', 'Wirkung', 'n'],
    ['评估', 'pínggū', 'bewerten, Evaluierung', 'v'],
    ['数据显示', 'shùjù xiǎnshì', 'die Daten zeigen', 's'],
    ['显示', 'xiǎnshì', 'zeigen, anzeigen', 'v'],
    ['指出', 'zhǐchū', 'darauf hinweisen', 'v'],
    ['分歧', 'fēnqí', 'Meinungsverschiedenheit', 'n']
  ],

  wirtschaft: [
    ['市场份额', 'shìchǎng fèn\'é', 'Marktanteil', 'n'],
    ['供求', 'gōngqiú', 'Angebot und Nachfrage', 'n'],
    ['需求', 'xūqiú', 'Nachfrage, Bedarf', 'n'],
    ['供应', 'gōngyìng', 'Versorgung, beliefern', 'n'],
    ['供应链', 'gōngyìngliàn', 'Lieferkette', 'n'],
    ['成本控制', 'chéngběn kòngzhì', 'Kostenkontrolle', 'n'],
    ['营业额', 'yíngyè\'é', 'Umsatz', 'n', 'Qùnián de yíngyè\'é zēngzhǎng le bǎifēnzhī shí.', 'Der Umsatz ist letztes Jahr um 10 % gestiegen.', '去年的营业额增长了百分之十。'],
    ['亏损', 'kuīsǔn', 'Verlust machen', 'v'],
    ['盈利', 'yínglì', 'Gewinn erzielen', 'v'],
    ['股份', 'gǔfèn', 'Aktie, Anteil', 'n'],
    ['股东', 'gǔdōng', 'Aktionär', 'n'],
    ['上市', 'shàngshì', 'an die Börse gehen', 'v'],
    ['融资', 'róngzī', 'Kapital beschaffen', 'v'],
    ['风险', 'fēngxiǎn', 'Risiko', 'n'],
    ['收益', 'shōuyì', 'Ertrag, Rendite', 'n'],
    ['预期', 'yùqī', 'Erwartung, erwarten', 'n'],
    ['波动', 'bōdòng', 'schwanken, Schwankung', 'v'],
    ['垄断', 'lǒngduàn', 'Monopol', 'n'],
    ['合并', 'hébìng', 'fusionieren', 'v'],
    ['破产', 'pòchǎn', 'Insolvenz, bankrott gehen', 'v'],
    ['合资', 'hézī', 'Joint Venture', 'n'],
    ['代理', 'dàilǐ', 'Vertretung, vertreten', 'n'],
    ['报价', 'bàojià', 'Angebot, Preisangebot', 'n'],
    ['议价', 'yìjià', 'über den Preis verhandeln', 'v'],
    ['条款', 'tiáokuǎn', 'Vertragsklausel', 'n'],
    ['违约', 'wéiyuē', 'vertragsbrüchig werden', 'v'],
    ['赔偿', 'péicháng', 'Schadensersatz leisten', 'v'],
    ['税收', 'shuìshōu', 'Steueraufkommen', 'n'],
    ['关税', 'guānshuì', 'Zoll', 'n'],
    ['补贴', 'bǔtiē', 'Subvention', 'n'],
    ['产业', 'chǎnyè', 'Industrie, Wirtschaftszweig', 'n'],
    ['升级', 'shēngjí', 'aufwerten, hochstufen', 'v'],
    ['转型', 'zhuǎnxíng', 'Strukturwandel vollziehen', 'v'],
    ['规模', 'guīmó', 'Größenordnung', 'n'],
    ['品牌', 'pǐnpái', 'Marke', 'n'],
    ['营销', 'yíngxiāo', 'Marketing', 'n'],
    ['渠道', 'qúdào', 'Vertriebsweg, Kanal', 'n'],
    ['电商', 'diànshāng', 'E-Commerce', 'n'],
    ['全球化', 'quánqiúhuà', 'Globalisierung', 'n'],
    ['劳动力', 'láodònglì', 'Arbeitskräfte', 'n']
  ]

});
