/* Pinyin-Pfad – Wortschatz A2
 * Format: [hanzi, pinyin, deutsch, wortart, beispielPinyin?, beispielDe?, beispielHanzi?]
 */
VokabelDaten.add('A2', {

  begruessung: [
    ['欢迎', 'huānyíng', 'willkommen heißen', 'v', 'Huānyíng nǐ lái wǒ jiā.', 'Willkommen bei mir zu Hause.', '欢迎你来我家。'],
    ['介绍', 'jièshào', 'vorstellen', 'v'],
    ['自己', 'zìjǐ', 'selbst', 's'],
    ['一起', 'yìqǐ', 'zusammen', 'd'],
    ['当然', 'dāngrán', 'selbstverständlich', 'd'],
    ['可能', 'kěnéng', 'vielleicht, möglich', 'd'],
    ['一定', 'yídìng', 'bestimmt, unbedingt', 'd'],
    ['别', 'bié', 'nicht (Verbot)', 'd', 'Bié shuōhuà!', 'Sprich nicht!', '别说话！'],
    ['好久不见', 'hǎojiǔ bú jiàn', 'lange nicht gesehen', 's'],
    ['麻烦', 'máfan', 'Umstände machen, lästig', 'v'],
    ['客气', 'kèqi', 'höflich, zurückhaltend', 'a'],
    ['祝', 'zhù', 'wünschen', 'v', 'Zhù nǐ shēngrì kuàilè!', 'Alles Gute zum Geburtstag!', '祝你生日快乐！'],
    ['聊天', 'liáotiān', 'plaudern', 'v'],
    ['告诉', 'gàosu', 'mitteilen, sagen', 'v'],
    ['懂事', 'dǒngshì', 'verständig sein', 'a']
  ],

  zahlen: [
    ['以前', 'yǐqián', 'früher, vorher', 'n', 'Yǐqián wǒ zhù zài Nánjīng.', 'Früher habe ich in Nanjing gewohnt.', '以前我住在南京。'],
    ['以后', 'yǐhòu', 'später, danach', 'n'],
    ['最近', 'zuìjìn', 'in letzter Zeit', 'd'],
    ['已经', 'yǐjīng', 'bereits, schon', 'd', 'Tā yǐjīng zǒu le.', 'Er ist schon gegangen.', '他已经走了。'],
    ['刚才', 'gāngcái', 'gerade eben', 'd'],
    ['马上', 'mǎshàng', 'sofort', 'd'],
    ['一会儿', 'yíhuìr', 'einen Augenblick', 's'],
    ['每', 'měi', 'jeder', 's'],
    ['次', 'cì', 'Mal (Häufigkeit)', 'p', 'Wǒ qù guo sān cì.', 'Ich war dreimal dort.', '我去过三次。'],
    ['遍', 'biàn', 'Mal (ganzer Durchgang)', 'p'],
    ['常常', 'chángcháng', 'oft', 'd'],
    ['有时候', 'yǒu shíhou', 'manchmal', 'd'],
    ['从来', 'cónglái', 'jemals, von jeher', 'd'],
    ['终于', 'zhōngyú', 'schließlich, endlich', 'd'],
    ['周末', 'zhōumò', 'Wochenende', 'n'],
    ['生日', 'shēngrì', 'Geburtstag', 'n'],
    ['迟到', 'chídào', 'zu spät kommen', 'v']
  ],

  familie: [
    ['亲戚', 'qīnqi', 'Verwandte', 'n'],
    ['叔叔', 'shūshu', 'Onkel (jüngerer Bruder des Vaters)', 'n'],
    ['阿姨', 'āyí', 'Tante', 'n'],
    ['外公', 'wàigōng', 'Großvater (mütterlich)', 'n'],
    ['外婆', 'wàipó', 'Großmutter (mütterlich)', 'n'],
    ['丈夫', 'zhàngfu', 'Ehemann', 'n'],
    ['妻子', 'qīzi', 'Ehefrau', 'n'],
    ['邻居', 'línjū', 'Nachbar', 'n'],
    ['照顾', 'zhàogù', 'sich kümmern um', 'v', 'Tā zhàogù shēngbìng de māma.', 'Sie kümmert sich um ihre kranke Mutter.', '她照顾生病的妈妈。'],
    ['关心', 'guānxīn', 'sich sorgen um', 'v'],
    ['长大', 'zhǎngdà', 'aufwachsen', 'v'],
    ['相信', 'xiāngxìn', 'glauben, vertrauen', 'v'],
    ['熟悉', 'shúxī', 'vertraut sein mit', 'a'],
    ['孤单', 'gūdān', 'einsam', 'a']
  ],

  essen: [
    ['早餐', 'zǎocān', 'Frühstück (gehoben)', 'n'],
    ['菜单', 'càidān', 'Speisekarte', 'n', 'Qǐng gěi wǒ càidān.', 'Bitte geben Sie mir die Speisekarte.', '请给我菜单。'],
    ['饮料', 'yǐnliào', 'Getränk', 'n'],
    ['果汁', 'guǒzhī', 'Fruchtsaft', 'n'],
    ['蔬菜', 'shūcài', 'Gemüse', 'n'],
    ['西红柿', 'xīhóngshì', 'Tomate', 'n'],
    ['土豆', 'tǔdòu', 'Kartoffel', 'n'],
    ['牛肉', 'niúròu', 'Rindfleisch', 'n'],
    ['猪肉', 'zhūròu', 'Schweinefleisch', 'n'],
    ['鸡肉', 'jīròu', 'Hühnerfleisch', 'n'],
    ['海鲜', 'hǎixiān', 'Meeresfrüchte', 'n'],
    ['味道', 'wèidào', 'Geschmack', 'n', 'Zhè dào cài wèidào bú cuò.', 'Dieses Gericht schmeckt nicht schlecht.', '这道菜味道不错。'],
    ['酸', 'suān', 'sauer', 'a'],
    ['咸', 'xián', 'salzig', 'a'],
    ['苦', 'kǔ', 'bitter', 'a'],
    ['饱', 'bǎo', 'satt', 'a'],
    ['尝', 'cháng', 'kosten, probieren', 'v'],
    ['做饭', 'zuòfàn', 'kochen', 'v'],
    ['请客', 'qǐngkè', 'einladen (zum Essen)', 'v'],
    ['打包', 'dǎbāo', 'einpacken lassen', 'v'],
    ['勺子', 'sháozi', 'Löffel', 'n']
  ],

  einkaufen: [
    ['价格', 'jiàgé', 'Preis', 'n'],
    ['打折', 'dǎzhé', 'Rabatt geben', 'v', 'Zhè jiàn yīfu dǎ bā zhé.', 'Auf dieses Kleidungsstück gibt es 20 % Rabatt.', '这件衣服打八折。'],
    ['便宜点儿', 'piányi diǎnr', 'etwas billiger', 's'],
    ['现金', 'xiànjīn', 'Bargeld', 'n'],
    ['刷卡', 'shuākǎ', 'mit Karte zahlen', 'v'],
    ['发票', 'fāpiào', 'Quittung, Rechnung', 'n'],
    ['顾客', 'gùkè', 'Kunde', 'n'],
    ['市场', 'shìchǎng', 'Markt', 'n'],
    ['商场', 'shāngchǎng', 'Einkaufszentrum', 'n'],
    ['试', 'shì', 'probieren, versuchen', 'v', 'Wǒ kěyǐ shì yíxià ma?', 'Darf ich es einmal anprobieren?', '我可以试一下吗？'],
    ['换', 'huàn', 'tauschen, wechseln', 'v'],
    ['退', 'tuì', 'zurückgeben', 'v'],
    ['质量', 'zhìliàng', 'Qualität', 'n'],
    ['选择', 'xuǎnzé', 'auswählen', 'v'],
    ['花', 'huā', 'ausgeben (Geld, Zeit)', 'v'],
    ['省', 'shěng', 'sparen', 'v']
  ],

  wohnen: [
    ['公寓', 'gōngyù', 'Wohnung', 'n'],
    ['租', 'zū', 'mieten', 'v', 'Wǒ zū le yí tào gōngyù.', 'Ich habe eine Wohnung gemietet.', '我租了一套公寓。'],
    ['房租', 'fángzū', 'Miete', 'n'],
    ['搬家', 'bānjiā', 'umziehen', 'v'],
    ['家具', 'jiājù', 'Möbel', 'n'],
    ['沙发', 'shāfā', 'Sofa', 'n'],
    ['空调', 'kōngtiáo', 'Klimaanlage', 'n'],
    ['洗衣机', 'xǐyījī', 'Waschmaschine', 'n'],
    ['打扫', 'dǎsǎo', 'putzen, aufräumen', 'v'],
    ['洗', 'xǐ', 'waschen', 'v'],
    ['整齐', 'zhěngqí', 'ordentlich', 'a'],
    ['安静', 'ānjìng', 'ruhig, still', 'a', 'Zhè ge xiǎoqū hěn ānjìng.', 'Dieses Viertel ist sehr ruhig.', '这个小区很安静。'],
    ['吵', 'chǎo', 'laut, lärmend', 'a'],
    ['修', 'xiū', 'reparieren', 'v'],
    ['电梯', 'diàntī', 'Aufzug', 'n'],
    ['院子', 'yuànzi', 'Hof, Garten', 'n']
  ],

  koerper: [
    ['胳膊', 'gēbo', 'Arm', 'n'],
    ['腿', 'tuǐ', 'Bein', 'n'],
    ['肚子', 'dùzi', 'Bauch', 'n'],
    ['脸', 'liǎn', 'Gesicht', 'n'],
    ['头发', 'tóufa', 'Haar', 'n'],
    ['牙', 'yá', 'Zahn', 'n'],
    ['感冒', 'gǎnmào', 'Erkältung, sich erkälten', 'v', 'Wǒ gǎnmào le.', 'Ich habe mich erkältet.', '我感冒了。'],
    ['发烧', 'fāshāo', 'Fieber haben', 'v'],
    ['咳嗽', 'késou', 'husten', 'v'],
    ['难受', 'nánshòu', 'sich unwohl fühlen', 'a'],
    ['检查', 'jiǎnchá', 'untersuchen, prüfen', 'v'],
    ['健康', 'jiànkāng', 'gesund, Gesundheit', 'a'],
    ['药店', 'yàodiàn', 'Apotheke', 'n'],
    ['吃药', 'chī yào', 'Medizin einnehmen', 'v'],
    ['受伤', 'shòushāng', 'sich verletzen', 'v'],
    ['住院', 'zhùyuàn', 'ins Krankenhaus aufgenommen werden', 'v'],
    ['锻炼', 'duànliàn', 'sich körperlich betätigen', 'v'],
    ['胖', 'pàng', 'dick, füllig', 'a'],
    ['瘦', 'shòu', 'dünn, schlank', 'a']
  ],

  kleidung: [
    ['衬衫', 'chènshān', 'Hemd, Bluse', 'n'],
    ['外套', 'wàitào', 'Jacke, Mantel', 'n'],
    ['毛衣', 'máoyī', 'Pullover', 'n'],
    ['袜子', 'wàzi', 'Socken', 'n'],
    ['手套', 'shǒutào', 'Handschuh', 'n'],
    ['围巾', 'wéijīn', 'Schal', 'n'],
    ['尺码', 'chǐmǎ', 'Kleidergröße', 'n', 'Nín chuān duō dà chǐmǎ?', 'Welche Größe tragen Sie?', '您穿多大尺码？'],
    ['合适', 'héshì', 'passend, geeignet', 'a'],
    ['脱', 'tuō', 'ausziehen', 'v'],
    ['时尚', 'shíshàng', 'modisch', 'a'],
    ['棉', 'mián', 'Baumwolle', 'n'],
    ['皮', 'pí', 'Leder, Haut', 'n']
  ],

  wetter: [
    ['阴', 'yīn', 'bewölkt', 'a'],
    ['晴', 'qíng', 'heiter, sonnig', 'a', 'Míngtiān shì qíngtiān.', 'Morgen wird es sonnig.', '明天是晴天。'],
    ['雾', 'wù', 'Nebel', 'n'],
    ['雷', 'léi', 'Donner', 'n'],
    ['刮风', 'guāfēng', 'windig sein', 'v'],
    ['气温', 'qìwēn', 'Lufttemperatur', 'n'],
    ['暖和', 'nuǎnhuo', 'warm, mild', 'a'],
    ['凉快', 'liángkuai', 'angenehm kühl', 'a'],
    ['潮湿', 'cháoshī', 'feucht', 'a'],
    ['干燥', 'gānzào', 'trocken', 'a'],
    ['季节', 'jìjié', 'Jahreszeit', 'n'],
    ['预报', 'yùbào', 'Vorhersage', 'n']
  ],

  verkehr: [
    ['地铁', 'dìtiě', 'U-Bahn', 'n', 'Zuò dìtiě bǐ kāichē kuài.', 'Mit der U-Bahn ist es schneller als mit dem Auto.', '坐地铁比开车快。'],
    ['船', 'chuán', 'Schiff', 'n'],
    ['骑', 'qí', 'fahren (Rad, Pferd)', 'v'],
    ['路上', 'lùshang', 'unterwegs', 'n'],
    ['堵车', 'dǔchē', 'Stau haben', 'v'],
    ['红绿灯', 'hónglǜdēng', 'Ampel', 'n'],
    ['司机', 'sījī', 'Fahrer', 'n'],
    ['行李', 'xíngli', 'Gepäck', 'n'],
    ['护照', 'hùzhào', 'Reisepass', 'n'],
    ['签证', 'qiānzhèng', 'Visum', 'n'],
    ['宾馆', 'bīnguǎn', 'Hotel', 'n'],
    ['房卡', 'fángkǎ', 'Zimmerkarte', 'n'],
    ['出发', 'chūfā', 'aufbrechen, losfahren', 'v'],
    ['到达', 'dàodá', 'ankommen', 'v'],
    ['起飞', 'qǐfēi', 'starten (Flugzeug)', 'v'],
    ['接', 'jiē', 'abholen, annehmen', 'v', 'Wǒ qù jīchǎng jiē nǐ.', 'Ich hole dich am Flughafen ab.', '我去机场接你。'],
    ['送', 'sòng', 'bringen, begleiten, schenken', 'v'],
    ['迷路', 'mílù', 'sich verlaufen', 'v'],
    ['路线', 'lùxiàn', 'Route, Linie', 'n'],
    ['安全', 'ānquán', 'sicher', 'a']
  ],

  richtungen: [
    ['东', 'dōng', 'Osten', 'n'],
    ['南', 'nán', 'Süden', 'n'],
    ['西', 'xī', 'Westen', 'n'],
    ['北', 'běi', 'Norden', 'n'],
    ['往', 'wǎng', 'in Richtung', 'p', 'Wǎng qián zǒu.', 'Gehen Sie geradeaus.', '往前走。'],
    ['一直', 'yìzhí', 'geradeaus, ununterbrochen', 'd'],
    ['过', 'guò', 'vorbeigehen, überqueren', 'v'],
    ['附近', 'fùjìn', 'Umgebung, in der Nähe', 'n'],
    ['楼上', 'lóushàng', 'oben im Haus', 'n'],
    ['楼下', 'lóuxià', 'unten im Haus', 'n'],
    ['方向', 'fāngxiàng', 'Richtung', 'n'],
    ['位置', 'wèizhi', 'Position, Lage', 'n']
  ],

  schule: [
    ['作业', 'zuòyè', 'Hausaufgabe', 'n', 'Wǒ hái méi zuò wán zuòyè.', 'Ich bin mit den Hausaufgaben noch nicht fertig.', '我还没做完作业。'],
    ['成绩', 'chéngjì', 'Note, Leistung', 'n'],
    ['练习', 'liànxí', 'üben, Übung', 'v'],
    ['复习', 'fùxí', 'wiederholen (Lernstoff)', 'v'],
    ['预习', 'yùxí', 'vorbereiten (Lernstoff)', 'v'],
    ['课本', 'kèběn', 'Lehrbuch', 'n'],
    ['词典', 'cídiǎn', 'Wörterbuch', 'n'],
    ['单词', 'dāncí', 'Vokabel', 'n'],
    ['语法', 'yǔfǎ', 'Grammatik', 'n'],
    ['发音', 'fāyīn', 'Aussprache', 'n'],
    ['翻译', 'fānyì', 'übersetzen, Übersetzer', 'v'],
    ['专业', 'zhuānyè', 'Studienfach', 'n'],
    ['毕业', 'bìyè', 'Abschluss machen', 'v'],
    ['报名', 'bàomíng', 'sich anmelden', 'v'],
    ['努力', 'nǔlì', 'sich anstrengen', 'a', 'Tā xuéxí hěn nǔlì.', 'Er lernt sehr fleißig.', '他学习很努力。'],
    ['进步', 'jìnbù', 'Fortschritt machen', 'v'],
    ['教', 'jiāo', 'unterrichten, beibringen', 'v'],
    ['解释', 'jiěshì', 'erklären', 'v']
  ],

  arbeit: [
    ['职业', 'zhíyè', 'Beruf', 'n'],
    ['面试', 'miànshì', 'Vorstellungsgespräch', 'n'],
    ['简历', 'jiǎnlì', 'Lebenslauf', 'n'],
    ['工资', 'gōngzī', 'Gehalt', 'n'],
    ['加班', 'jiābān', 'Überstunden machen', 'v', 'Zhè ge xīngqī wǒ tiāntiān jiābān.', 'Diese Woche mache ich jeden Tag Überstunden.', '这个星期我天天加班。'],
    ['请假', 'qǐngjià', 'sich freinehmen', 'v'],
    ['出差', 'chūchāi', 'Dienstreise machen', 'v'],
    ['任务', 'rènwu', 'Aufgabe, Auftrag', 'n'],
    ['计划', 'jìhuà', 'Plan, planen', 'n'],
    ['准备', 'zhǔnbèi', 'vorbereiten', 'v'],
    ['完成', 'wánchéng', 'abschließen, fertigstellen', 'v'],
    ['顺利', 'shùnlì', 'reibungslos', 'a'],
    ['负责', 'fùzé', 'verantwortlich sein', 'v'],
    ['经验', 'jīngyàn', 'Erfahrung', 'n'],
    ['能力', 'nénglì', 'Fähigkeit', 'n'],
    ['护士', 'hùshi', 'Krankenpfleger, Krankenschwester', 'n'],
    ['警察', 'jǐngchá', 'Polizist', 'n'],
    ['厨师', 'chúshī', 'Koch', 'n']
  ],

  freizeit: [
    ['小说', 'xiǎoshuō', 'Roman', 'n'],
    ['杂志', 'zázhì', 'Zeitschrift', 'n'],
    ['报纸', 'bàozhǐ', 'Zeitung', 'n'],
    ['演出', 'yǎnchū', 'Aufführung', 'n'],
    ['聚会', 'jùhuì', 'Treffen, Party', 'n', 'Zhōumò wǒmen yǒu yí ge jùhuì.', 'Am Wochenende haben wir ein Treffen.', '周末我们有一个聚会。'],
    ['散步', 'sànbù', 'spazieren gehen', 'v'],
    ['拍照', 'pāizhào', 'fotografieren', 'v'],
    ['画画儿', 'huàhuàr', 'malen', 'v'],
    ['下棋', 'xiàqí', 'Schach spielen', 'v'],
    ['钓鱼', 'diàoyú', 'angeln', 'v'],
    ['爬山', 'páshān', 'bergsteigen', 'v'],
    ['参加', 'cānjiā', 'teilnehmen an', 'v'],
    ['无聊', 'wúliáo', 'langweilig', 'a'],
    ['热闹', 'rènao', 'lebhaft, belebt', 'a'],
    ['放假', 'fàngjià', 'Ferien haben', 'v'],
    ['安排', 'ānpái', 'einteilen, arrangieren', 'v']
  ],

  sport: [
    ['羽毛球', 'yǔmáoqiú', 'Badminton', 'n'],
    ['乒乓球', 'pīngpāngqiú', 'Tischtennis', 'n'],
    ['网球', 'wǎngqiú', 'Tennis', 'n'],
    ['队', 'duì', 'Mannschaft', 'n'],
    ['输', 'shū', 'verlieren', 'v', 'Wǒmen shū le bǐsài.', 'Wir haben das Spiel verloren.', '我们输了比赛。'],
    ['赢', 'yíng', 'gewinnen', 'v'],
    ['教练', 'jiàoliàn', 'Trainer', 'n'],
    ['体育', 'tǐyù', 'Sport (als Fach)', 'n'],
    ['健身房', 'jiànshēnfáng', 'Fitnessstudio', 'n'],
    ['跳', 'tiào', 'springen', 'v'],
    ['力气', 'lìqi', 'Kraft', 'n'],
    ['坚持', 'jiānchí', 'durchhalten, beharren', 'v']
  ],

  natur: [
    ['动物', 'dòngwù', 'Tier', 'n'],
    ['植物', 'zhíwù', 'Pflanze', 'n'],
    ['森林', 'sēnlín', 'Wald', 'n'],
    ['湖', 'hú', 'See', 'n'],
    ['沙漠', 'shāmò', 'Wüste', 'n'],
    ['空气', 'kōngqì', 'Luft', 'n', 'Shān shàng de kōngqì hěn xīnxiān.', 'Die Luft in den Bergen ist sehr frisch.', '山上的空气很新鲜。'],
    ['环境', 'huánjìng', 'Umwelt, Umgebung', 'n'],
    ['保护', 'bǎohù', 'schützen', 'v'],
    ['老虎', 'lǎohǔ', 'Tiger', 'n'],
    ['熊猫', 'xióngmāo', 'Panda', 'n'],
    ['羊', 'yáng', 'Schaf', 'n'],
    ['猪', 'zhū', 'Schwein', 'n'],
    ['虫子', 'chóngzi', 'Insekt', 'n'],
    ['新鲜', 'xīnxiān', 'frisch', 'a']
  ],

  technik: [
    ['短信', 'duǎnxìn', 'SMS, Kurznachricht', 'n'],
    ['邮件', 'yóujiàn', 'E-Mail, Post', 'n', 'Wǒ gěi nǐ fā le yì fēng yóujiàn.', 'Ich habe dir eine E-Mail geschickt.', '我给你发了一封邮件。'],
    ['网站', 'wǎngzhàn', 'Webseite', 'n'],
    ['密码', 'mìmǎ', 'Passwort', 'n'],
    ['文件', 'wénjiàn', 'Datei, Dokument', 'n'],
    ['下载', 'xiàzài', 'herunterladen', 'v'],
    ['软件', 'ruǎnjiàn', 'Software', 'n'],
    ['充电', 'chōngdiàn', 'aufladen', 'v'],
    ['键盘', 'jiànpán', 'Tastatur', 'n'],
    ['屏幕', 'píngmù', 'Bildschirm', 'n'],
    ['打印', 'dǎyìn', 'drucken', 'v'],
    ['关机', 'guānjī', 'ausschalten (Gerät)', 'v'],
    ['声音', 'shēngyīn', 'Ton, Stimme', 'n'],
    ['节目', 'jiémù', 'Programm, Sendung', 'n']
  ],

  gefuehle: [
    ['开心', 'kāixīn', 'gut gelaunt', 'a'],
    ['满意', 'mǎnyì', 'zufrieden', 'a', 'Lǎobǎn duì jiéguǒ hěn mǎnyì.', 'Der Chef ist mit dem Ergebnis sehr zufrieden.', '老板对结果很满意。'],
    ['担心', 'dānxīn', 'sich Sorgen machen', 'v'],
    ['着急', 'zháojí', 'ungeduldig, in Eile sein', 'a'],
    ['紧张', 'jǐnzhāng', 'nervös, angespannt', 'a'],
    ['放松', 'fàngsōng', 'entspannen', 'v'],
    ['害怕', 'hàipà', 'sich fürchten', 'v'],
    ['奇怪', 'qíguài', 'seltsam', 'a'],
    ['吃惊', 'chījīng', 'überrascht sein', 'v'],
    ['感动', 'gǎndòng', 'gerührt sein', 'v'],
    ['骄傲', 'jiāo\'ào', 'stolz', 'a'],
    ['耐心', 'nàixīn', 'Geduld', 'n'],
    ['诚实', 'chéngshí', 'ehrlich', 'a'],
    ['聪明', 'cōngming', 'klug', 'a'],
    ['懒', 'lǎn', 'faul', 'a'],
    ['认真', 'rènzhēn', 'gewissenhaft', 'a']
  ],

  farben: [
    ['紫', 'zǐ', 'lila, violett', 'a'],
    ['粉红', 'fěnhóng', 'rosa', 'a'],
    ['橙色', 'chéngsè', 'orange', 'a'],
    ['深', 'shēn', 'dunkel, tief', 'a'],
    ['浅', 'qiǎn', 'hell, flach', 'a'],
    ['方形', 'fāngxíng', 'Quadrat, viereckig', 'n'],
    ['三角形', 'sānjiǎoxíng', 'Dreieck', 'n'],
    ['形状', 'xíngzhuàng', 'Form', 'n'],
    ['宽', 'kuān', 'breit', 'a'],
    ['厚', 'hòu', 'dick (Material)', 'a']
  ],

  stadt: [
    ['首都', 'shǒudū', 'Hauptstadt', 'n'],
    ['农村', 'nóngcūn', 'Dorf, ländliche Gegend', 'n'],
    ['广场', 'guǎngchǎng', 'Platz', 'n'],
    ['图书馆', 'túshūguǎn', 'Bibliothek', 'n'],
    ['博物馆', 'bówùguǎn', 'Museum', 'n'],
    ['体育馆', 'tǐyùguǎn', 'Sporthalle', 'n'],
    ['大使馆', 'dàshǐguǎn', 'Botschaft', 'n'],
    ['警察局', 'jǐngchájú', 'Polizeiwache', 'n'],
    ['人口', 'rénkǒu', 'Bevölkerung', 'n', 'Zhè ge chéngshì rénkǒu hěn duō.', 'Diese Stadt hat sehr viele Einwohner.', '这个城市人口很多。'],
    ['交通', 'jiāotōng', 'Verkehr', 'n'],
    ['繁华', 'fánhuá', 'florierend, geschäftig', 'a'],
    ['方便', 'fāngbiàn', 'praktisch, bequem', 'a'],
    ['省份', 'shěngfèn', 'Provinz', 'n'],
    ['邻国', 'línguó', 'Nachbarland', 'n']
  ],

  feste: [
    ['春节', 'Chūnjié', 'Frühlingsfest, chinesisches Neujahr', 'n', 'Chūnjié shí quánjiā tuánjù.', 'Zum Frühlingsfest kommt die ganze Familie zusammen.', '春节时全家团聚。'],
    ['中秋节', 'Zhōngqiūjié', 'Mondfest', 'n'],
    ['节日', 'jiérì', 'Feiertag, Fest', 'n'],
    ['礼物', 'lǐwù', 'Geschenk', 'n'],
    ['红包', 'hóngbāo', 'roter Umschlag (Geldgeschenk)', 'n'],
    ['庆祝', 'qìngzhù', 'feiern', 'v'],
    ['放烟花', 'fàng yānhuā', 'Feuerwerk zünden', 'v'],
    ['团聚', 'tuánjù', 'sich versammeln (Familie)', 'v'],
    ['月饼', 'yuèbǐng', 'Mondkuchen', 'n'],
    ['传统', 'chuántǒng', 'Tradition, traditionell', 'n']
  ]

});
