/* Pinyin-Pfad – Wortschatz B1
 * Format: [hanzi, pinyin, deutsch, wortart, beispielPinyin?, beispielDe?, beispielHanzi?]
 */
VokabelDaten.add('B1', {

  begruessung: [
    ['打招呼', 'dǎ zhāohu', 'jemanden grüßen', 'v'],
    ['称呼', 'chēnghu', 'Anrede, anreden', 'n'],
    ['随便', 'suíbiàn', 'wie du willst, ungezwungen', 'a', 'Chī shénme dōu xíng, wǒ suíbiàn.', 'Ich esse alles, mir ist es gleich.', '吃什么都行，我随便。'],
    ['打扰', 'dǎrǎo', 'stören', 'v'],
    ['客套', 'kètào', 'Höflichkeitsfloskel', 'n'],
    ['联系', 'liánxì', 'Kontakt aufnehmen, Verbindung', 'v'],
    ['保持', 'bǎochí', 'aufrechterhalten, beibehalten', 'v'],
    ['印象', 'yìnxiàng', 'Eindruck', 'n', 'Tā gěi wǒ liú xià le hěn hǎo de yìnxiàng.', 'Er hat bei mir einen sehr guten Eindruck hinterlassen.', '他给我留下了很好的印象。'],
    ['热情', 'rèqíng', 'herzlich, gastfreundlich', 'a'],
    ['礼貌', 'lǐmào', 'Höflichkeit, höflich', 'n'],
    ['表达', 'biǎodá', 'ausdrücken', 'v'],
    ['沟通', 'gōutōng', 'sich verständigen', 'v'],
    ['误会', 'wùhuì', 'Missverständnis, missverstehen', 'n'],
    ['道歉', 'dàoqiàn', 'sich entschuldigen', 'v'],
    ['邀请', 'yāoqǐng', 'einladen', 'v'],
    ['拒绝', 'jùjué', 'ablehnen', 'v']
  ],

  zahlen: [
    ['大约', 'dàyuē', 'ungefähr', 'd'],
    ['左右', 'zuǒyòu', 'etwa, ungefähr (nachgestellt)', 's', 'Sānshí suì zuǒyòu.', 'Etwa dreißig Jahre alt.', '三十岁左右。'],
    ['将近', 'jiāngjìn', 'nahezu', 'd'],
    ['至少', 'zhìshǎo', 'mindestens', 'd'],
    ['最多', 'zuìduō', 'höchstens', 'd'],
    ['倍', 'bèi', 'Mal (Vielfaches)', 'p', 'Jiàgé zhǎng le yí bèi.', 'Der Preis hat sich verdoppelt.', '价格涨了一倍。'],
    ['百分之', 'bǎifēnzhī', 'Prozent', 's'],
    ['平均', 'píngjūn', 'durchschnittlich', 'a'],
    ['期间', 'qījiān', 'Zeitraum, während', 'n'],
    ['同时', 'tóngshí', 'gleichzeitig', 'd'],
    ['按时', 'ànshí', 'pünktlich, termingerecht', 'd'],
    ['提前', 'tíqián', 'vorziehen, im Voraus', 'v'],
    ['推迟', 'tuīchí', 'verschieben', 'v'],
    ['临时', 'línshí', 'vorübergehend, kurzfristig', 'a'],
    ['日期', 'rìqī', 'Datum', 'n'],
    ['世纪', 'shìjì', 'Jahrhundert', 'n']
  ],

  familie: [
    ['家庭', 'jiātíng', 'Familie (als Einheit)', 'n'],
    ['夫妻', 'fūqī', 'Ehepaar', 'n'],
    ['亲爱', 'qīn\'ài', 'lieb, teuer', 'a'],
    ['恋爱', 'liàn\'ài', 'Liebesbeziehung, verliebt sein', 'n'],
    ['离婚', 'líhūn', 'sich scheiden lassen', 'v'],
    ['怀孕', 'huáiyùn', 'schwanger sein', 'v'],
    ['教育', 'jiàoyù', 'Erziehung, erziehen', 'n', 'Fùmǔ duì háizi de jiàoyù hěn zhòngyào.', 'Die Erziehung der Kinder durch die Eltern ist sehr wichtig.', '父母对孩子的教育很重要。'],
    ['父母', 'fùmǔ', 'Eltern', 'n'],
    ['独生子女', 'dúshēng zǐnǚ', 'Einzelkind', 'n'],
    ['养', 'yǎng', 'aufziehen, halten', 'v'],
    ['尊重', 'zūnzhòng', 'respektieren', 'v'],
    ['吵架', 'chǎojià', 'sich streiten', 'v'],
    ['和好', 'héhǎo', 'sich versöhnen', 'v'],
    ['分手', 'fēnshǒu', 'sich trennen', 'v'],
    ['信任', 'xìnrèn', 'Vertrauen, vertrauen', 'n'],
    ['支持', 'zhīchí', 'unterstützen', 'v'],
    ['陪', 'péi', 'begleiten, Gesellschaft leisten', 'v'],
    ['代沟', 'dàigōu', 'Generationenkluft', 'n']
  ],

  essen: [
    ['餐厅', 'cāntīng', 'Restaurant, Speisesaal', 'n'],
    ['食物', 'shíwù', 'Nahrungsmittel', 'n'],
    ['营养', 'yíngyǎng', 'Nährstoff, Ernährung', 'n', 'Zhè zhǒng shíwù yíngyǎng hěn fēngfù.', 'Dieses Nahrungsmittel ist sehr nährstoffreich.', '这种食物营养很丰富。'],
    ['食谱', 'shípǔ', 'Rezept', 'n'],
    ['材料', 'cáiliào', 'Zutat, Material', 'n'],
    ['切', 'qiē', 'schneiden', 'v'],
    ['炒', 'chǎo', 'pfannenrühren, braten', 'v'],
    ['煮', 'zhǔ', 'kochen (in Wasser)', 'v'],
    ['蒸', 'zhēng', 'dämpfen', 'v'],
    ['烤', 'kǎo', 'backen, grillen', 'v'],
    ['口味', 'kǒuwèi', 'Geschmacksrichtung', 'n'],
    ['清淡', 'qīngdàn', 'leicht, mild gewürzt', 'a'],
    ['油腻', 'yóunì', 'fettig', 'a'],
    ['素食', 'sùshí', 'vegetarische Kost', 'n'],
    ['浪费', 'làngfèi', 'verschwenden', 'v'],
    ['份', 'fèn', 'Portion', 'p'],
    ['预订', 'yùdìng', 'reservieren', 'v'],
    ['结账', 'jiézhàng', 'die Rechnung begleichen', 'v'],
    ['小费', 'xiǎofèi', 'Trinkgeld', 'n'],
    ['特色', 'tèsè', 'Besonderheit, charakteristisch', 'n']
  ],

  einkaufen: [
    ['消费', 'xiāofèi', 'konsumieren, Konsum', 'v'],
    ['优惠', 'yōuhuì', 'Vergünstigung', 'n'],
    ['促销', 'cùxiāo', 'Verkaufsaktion', 'n'],
    ['预算', 'yùsuàn', 'Budget', 'n', 'Wǒ de yùsuàn bù gāo.', 'Mein Budget ist nicht hoch.', '我的预算不高。'],
    ['结算', 'jiésuàn', 'abrechnen', 'v'],
    ['支付', 'zhīfù', 'bezahlen (formell)', 'v'],
    ['账户', 'zhànghù', 'Konto', 'n'],
    ['存钱', 'cún qián', 'Geld einzahlen, sparen', 'v'],
    ['取钱', 'qǔ qián', 'Geld abheben', 'v'],
    ['借', 'jiè', 'leihen, ausleihen', 'v'],
    ['还', 'huán', 'zurückgeben', 'v'],
    ['讨价还价', 'tǎojià huánjià', 'feilschen', 'v'],
    ['划算', 'huásuàn', 'sich lohnen, günstig', 'a'],
    ['名牌', 'míngpái', 'Markenartikel', 'n'],
    ['假货', 'jiǎhuò', 'Fälschung', 'n'],
    ['网购', 'wǎnggòu', 'online einkaufen', 'v'],
    ['快递', 'kuàidì', 'Kurierdienst, Paket', 'n'],
    ['包装', 'bāozhuāng', 'Verpackung, verpacken', 'n']
  ],

  wohnen: [
    ['小区', 'xiǎoqū', 'Wohnviertel', 'n'],
    ['房东', 'fángdōng', 'Vermieter', 'n'],
    ['合同', 'hétong', 'Vertrag', 'n', 'Wǒmen qiān le yì nián de hétong.', 'Wir haben einen Vertrag über ein Jahr unterschrieben.', '我们签了一年的合同。'],
    ['押金', 'yājīn', 'Kaution', 'n'],
    ['装修', 'zhuāngxiū', 'renovieren, ausbauen', 'v'],
    ['家务', 'jiāwù', 'Hausarbeit', 'n'],
    ['垃圾', 'lājī', 'Müll', 'n'],
    ['分类', 'fēnlèi', 'sortieren, einordnen', 'v'],
    ['水电费', 'shuǐdiànfèi', 'Nebenkosten für Wasser und Strom', 'n'],
    ['阳台', 'yángtái', 'Balkon', 'n'],
    ['卧室', 'wòshì', 'Schlafzimmer', 'n'],
    ['地板', 'dìbǎn', 'Fußboden', 'n'],
    ['墙', 'qiáng', 'Wand', 'n'],
    ['舒适', 'shūshì', 'behaglich', 'a'],
    ['宽敞', 'kuānchang', 'geräumig', 'a'],
    ['拥挤', 'yōngjǐ', 'überfüllt, eng', 'a'],
    ['设备', 'shèbèi', 'Ausstattung, Anlage', 'n'],
    ['搬进', 'bān jìn', 'einziehen', 'v']
  ],

  koerper: [
    ['症状', 'zhèngzhuàng', 'Symptom', 'n'],
    ['疼痛', 'téngtòng', 'Schmerz', 'n'],
    ['过敏', 'guòmǐn', 'allergisch sein', 'v', 'Wǒ duì huāfěn guòmǐn.', 'Ich bin gegen Pollen allergisch.', '我对花粉过敏。'],
    ['头晕', 'tóuyūn', 'schwindelig sein', 'v'],
    ['呕吐', 'ǒutù', 'sich übergeben', 'v'],
    ['血', 'xuè', 'Blut', 'n'],
    ['心脏', 'xīnzàng', 'Herz (Organ)', 'n'],
    ['骨头', 'gǔtou', 'Knochen', 'n'],
    ['皮肤', 'pífū', 'Haut', 'n'],
    ['手术', 'shǒushù', 'Operation', 'n'],
    ['治疗', 'zhìliáo', 'behandeln, Therapie', 'v'],
    ['恢复', 'huīfù', 'sich erholen, wiederherstellen', 'v'],
    ['预防', 'yùfáng', 'vorbeugen', 'v'],
    ['疫苗', 'yìmiáo', 'Impfstoff', 'n'],
    ['保险', 'bǎoxiǎn', 'Versicherung', 'n'],
    ['体检', 'tǐjiǎn', 'Vorsorgeuntersuchung', 'n'],
    ['睡眠', 'shuìmián', 'Schlaf', 'n'],
    ['压力', 'yālì', 'Druck, Stress', 'n', 'Gōngzuò yālì tài dà le.', 'Der Arbeitsdruck ist zu groß.', '工作压力太大了。'],
    ['戒烟', 'jièyān', 'mit dem Rauchen aufhören', 'v'],
    ['急诊', 'jízhěn', 'Notaufnahme', 'n']
  ],

  kleidung: [
    ['西装', 'xīzhuāng', 'Anzug', 'n'],
    ['领带', 'lǐngdài', 'Krawatte', 'n'],
    ['牛仔裤', 'niúzǎikù', 'Jeans', 'n'],
    ['风格', 'fēnggé', 'Stil', 'n'],
    ['搭配', 'dāpèi', 'kombinieren', 'v', 'Zhè jiàn wàitào hé kùzi hěn dāpèi.', 'Diese Jacke passt gut zur Hose.', '这件外套和裤子很搭配。'],
    ['朴素', 'pǔsù', 'schlicht', 'a'],
    ['正式', 'zhèngshì', 'formell, offiziell', 'a'],
    ['休闲', 'xiūxián', 'leger, Freizeit-', 'a'],
    ['布', 'bù', 'Stoff', 'n'],
    ['洗涤', 'xǐdí', 'reinigen, waschen (fachsprachlich)', 'v'],
    ['破', 'pò', 'kaputt, zerrissen', 'a'],
    ['流行', 'liúxíng', 'in Mode sein', 'v']
  ],

  wetter: [
    ['天气预报', 'tiānqì yùbào', 'Wettervorhersage', 'n'],
    ['气候', 'qìhòu', 'Klima', 'n'],
    ['温度', 'wēndù', 'Temperatur', 'n'],
    ['零下', 'língxià', 'unter null', 's', 'Jīntiān língxià wǔ dù.', 'Heute sind es minus fünf Grad.', '今天零下五度。'],
    ['暴雨', 'bàoyǔ', 'Starkregen', 'n'],
    ['台风', 'táifēng', 'Taifun', 'n'],
    ['洪水', 'hóngshuǐ', 'Überschwemmung', 'n'],
    ['干旱', 'gānhàn', 'Dürre', 'n'],
    ['湿度', 'shīdù', 'Luftfeuchtigkeit', 'n'],
    ['变化', 'biànhuà', 'Veränderung, sich ändern', 'n'],
    ['灾害', 'zāihài', 'Naturkatastrophe', 'n'],
    ['晴朗', 'qínglǎng', 'klar und sonnig', 'a'],
    ['阴天', 'yīntiān', 'bedeckter Tag', 'n'],
    ['彩虹', 'cǎihóng', 'Regenbogen', 'n']
  ],

  verkehr: [
    ['航班', 'hángbān', 'Flug, Flugverbindung', 'n'],
    ['登机', 'dēngjī', 'an Bord gehen', 'v'],
    ['托运', 'tuōyùn', 'aufgeben (Gepäck)', 'v'],
    ['转机', 'zhuǎnjī', 'umsteigen (Flug)', 'v'],
    ['误点', 'wùdiǎn', 'Verspätung haben', 'v', 'Huǒchē wùdiǎn le bàn xiǎoshí.', 'Der Zug hatte eine halbe Stunde Verspätung.', '火车误点了半小时。'],
    ['高铁', 'gāotiě', 'Hochgeschwindigkeitszug', 'n'],
    ['候车室', 'hòuchēshì', 'Wartesaal', 'n'],
    ['站台', 'zhàntái', 'Bahnsteig', 'n'],
    ['单程', 'dānchéng', 'einfache Fahrt', 'n'],
    ['往返', 'wǎngfǎn', 'hin und zurück', 'n'],
    ['导游', 'dǎoyóu', 'Reiseführer (Person)', 'n'],
    ['景点', 'jǐngdiǎn', 'Sehenswürdigkeit', 'n'],
    ['纪念品', 'jìniànpǐn', 'Souvenir', 'n'],
    ['入住', 'rùzhù', 'einchecken (Hotel)', 'v'],
    ['退房', 'tuìfáng', 'auschecken', 'v'],
    ['驾照', 'jiàzhào', 'Führerschein', 'n'],
    ['加油站', 'jiāyóuzhàn', 'Tankstelle', 'n'],
    ['停车场', 'tíngchēchǎng', 'Parkplatz', 'n'],
    ['事故', 'shìgù', 'Unfall', 'n'],
    ['遵守', 'zūnshǒu', 'einhalten (Regeln)', 'v']
  ],

  richtungen: [
    ['东北', 'dōngběi', 'Nordosten', 'n'],
    ['西南', 'xīnán', 'Südwesten', 'n'],
    ['沿着', 'yánzhe', 'entlang', 'p', 'Yánzhe zhè tiáo lù zǒu.', 'Gehen Sie diese Straße entlang.', '沿着这条路走。'],
    ['穿过', 'chuānguò', 'durchqueren', 'v'],
    ['尽头', 'jìntóu', 'Ende (einer Strecke)', 'n'],
    ['入口', 'rùkǒu', 'Eingang', 'n'],
    ['出口', 'chūkǒu', 'Ausgang', 'n'],
    ['距离', 'jùlí', 'Entfernung', 'n'],
    ['周围', 'zhōuwéi', 'ringsum, Umgebung', 'n'],
    ['朝', 'cháo', 'in Richtung, zugewandt', 'p'],
    ['地区', 'dìqū', 'Region, Gebiet', 'n'],
    ['当地', 'dāngdì', 'örtlich, hiesig', 'a']
  ],

  schule: [
    ['知识', 'zhīshi', 'Wissen', 'n'],
    ['水平', 'shuǐpíng', 'Niveau, Kenntnisstand', 'n', 'Tā de Hànyǔ shuǐpíng tígāo le hěn duō.', 'Sein Chinesischniveau hat sich stark verbessert.', '他的汉语水平提高了很多。'],
    ['提高', 'tígāo', 'verbessern, steigern', 'v'],
    ['掌握', 'zhǎngwò', 'beherrschen', 'v'],
    ['记忆', 'jìyì', 'Gedächtnis, sich erinnern', 'n'],
    ['背', 'bèi', 'auswendig lernen', 'v'],
    ['讲座', 'jiǎngzuò', 'Vortrag', 'n'],
    ['论文', 'lùnwén', 'wissenschaftliche Arbeit', 'n'],
    ['奖学金', 'jiǎngxuéjīn', 'Stipendium', 'n'],
    ['学期', 'xuéqī', 'Semester', 'n'],
    ['留学', 'liúxué', 'im Ausland studieren', 'v'],
    ['申请', 'shēnqǐng', 'beantragen, sich bewerben', 'v'],
    ['录取', 'lùqǔ', 'zulassen, aufnehmen', 'v'],
    ['及格', 'jígé', 'bestehen (Prüfung)', 'v'],
    ['作文', 'zuòwén', 'Aufsatz', 'n'],
    ['笔记', 'bǐjì', 'Notizen', 'n'],
    ['课程', 'kèchéng', 'Lehrveranstaltung, Curriculum', 'n'],
    ['理论', 'lǐlùn', 'Theorie', 'n'],
    ['实践', 'shíjiàn', 'Praxis, praktisch anwenden', 'n'],
    ['举例', 'jǔlì', 'ein Beispiel geben', 'v'],
    ['总结', 'zǒngjié', 'zusammenfassen', 'v'],
    ['讨论', 'tǎolùn', 'diskutieren', 'v']
  ],

  arbeit: [
    ['职位', 'zhíwèi', 'Stelle, Position', 'n'],
    ['招聘', 'zhāopìn', 'Personal einstellen', 'v'],
    ['应聘', 'yìngpìn', 'sich auf eine Stelle bewerben', 'v'],
    ['录用', 'lùyòng', 'einstellen', 'v'],
    ['辞职', 'cízhí', 'kündigen (selbst)', 'v', 'Tā shàng ge yuè cízhí le.', 'Er hat letzten Monat gekündigt.', '他上个月辞职了。'],
    ['解雇', 'jiěgù', 'entlassen', 'v'],
    ['失业', 'shīyè', 'arbeitslos sein', 'v'],
    ['升职', 'shēngzhí', 'befördert werden', 'v'],
    ['合作', 'hézuò', 'zusammenarbeiten', 'v'],
    ['团队', 'tuánduì', 'Team', 'n'],
    ['效率', 'xiàolǜ', 'Effizienz', 'n'],
    ['处理', 'chǔlǐ', 'bearbeiten, erledigen', 'v'],
    ['汇报', 'huìbào', 'Bericht erstatten', 'v'],
    ['方案', 'fāng\'àn', 'Konzept, Entwurf', 'n'],
    ['目标', 'mùbiāo', 'Ziel', 'n'],
    ['期限', 'qīxiàn', 'Frist', 'n'],
    ['责任', 'zérèn', 'Verantwortung', 'n'],
    ['困难', 'kùnnan', 'Schwierigkeit, schwierig', 'n'],
    ['解决', 'jiějué', 'lösen', 'v', 'Zhè ge wèntí hěn nán jiějué.', 'Dieses Problem ist schwer zu lösen.', '这个问题很难解决。'],
    ['建议', 'jiànyì', 'Vorschlag, vorschlagen', 'n'],
    ['培训', 'péixùn', 'Schulung, schulen', 'n'],
    ['薪水', 'xīnshuǐ', 'Gehalt, Lohn', 'n'],
    ['福利', 'fúlì', 'Sozialleistungen', 'n'],
    ['同行', 'tóngháng', 'Branchenkollege', 'n']
  ],

  freizeit: [
    ['业余', 'yèyú', 'Freizeit-, nebenberuflich', 'a'],
    ['娱乐', 'yúlè', 'Unterhaltung', 'n'],
    ['展览', 'zhǎnlǎn', 'Ausstellung', 'n'],
    ['演唱会', 'yǎnchànghuì', 'Konzert', 'n'],
    ['戏剧', 'xìjù', 'Theaterstück', 'n'],
    ['文学', 'wénxué', 'Literatur', 'n'],
    ['作者', 'zuòzhě', 'Autor', 'n'],
    ['情节', 'qíngjié', 'Handlung (Geschichte)', 'n'],
    ['乐器', 'yuèqì', 'Musikinstrument', 'n'],
    ['弹', 'tán', 'spielen (Saiteninstrument)', 'v', 'Tā huì tán gāngqín.', 'Sie kann Klavier spielen.', '她会弹钢琴。'],
    ['钢琴', 'gāngqín', 'Klavier', 'n'],
    ['摄影', 'shèyǐng', 'Fotografie', 'n'],
    ['收藏', 'shōucáng', 'sammeln', 'v'],
    ['露营', 'lùyíng', 'zelten', 'v'],
    ['自由', 'zìyóu', 'Freiheit, frei', 'n'],
    ['消遣', 'xiāoqiǎn', 'Zeitvertreib', 'n'],
    ['兴趣', 'xìngqù', 'Interesse', 'n'],
    ['经历', 'jīnglì', 'Erlebnis, erleben', 'n'],
    ['体验', 'tǐyàn', 'erfahren, Erfahrung machen', 'v'],
    ['纪录片', 'jìlùpiàn', 'Dokumentarfilm', 'n']
  ],

  sport: [
    ['运动员', 'yùndòngyuán', 'Sportler', 'n'],
    ['冠军', 'guànjūn', 'Meister, Sieger', 'n'],
    ['奖牌', 'jiǎngpái', 'Medaille', 'n'],
    ['决赛', 'juésài', 'Finale', 'n'],
    ['纪录', 'jìlù', 'Rekord', 'n', 'Tā dǎpò le shìjiè jìlù.', 'Er hat den Weltrekord gebrochen.', '他打破了世界纪录。'],
    ['训练', 'xùnliàn', 'trainieren', 'v'],
    ['体力', 'tǐlì', 'körperliche Kraft', 'n'],
    ['规则', 'guīzé', 'Regel', 'n'],
    ['裁判', 'cáipàn', 'Schiedsrichter', 'n'],
    ['滑雪', 'huáxuě', 'Ski fahren', 'v'],
    ['武术', 'wǔshù', 'Kampfkunst', 'n'],
    ['太极拳', 'tàijíquán', 'Taijiquan', 'n'],
    ['马拉松', 'mǎlāsōng', 'Marathon', 'n'],
    ['放弃', 'fàngqì', 'aufgeben', 'v']
  ],

  natur: [
    ['自然', 'zìrán', 'Natur, natürlich', 'n'],
    ['资源', 'zīyuán', 'Ressource', 'n'],
    ['污染', 'wūrǎn', 'Verschmutzung, verschmutzen', 'n', 'Kōngqì wūrǎn yuè lái yuè yánzhòng.', 'Die Luftverschmutzung wird immer schlimmer.', '空气污染越来越严重。'],
    ['垃圾桶', 'lājītǒng', 'Mülleimer', 'n'],
    ['回收', 'huíshōu', 'recyceln', 'v'],
    ['节约', 'jiéyuē', 'sparsam umgehen mit', 'v'],
    ['能源', 'néngyuán', 'Energie (Ressource)', 'n'],
    ['太阳能', 'tàiyángnéng', 'Solarenergie', 'n'],
    ['野生', 'yěshēng', 'wild lebend', 'a'],
    ['濒危', 'bīnwēi', 'vom Aussterben bedroht', 'a'],
    ['物种', 'wùzhǒng', 'Art (Biologie)', 'n'],
    ['生态', 'shēngtài', 'Ökologie', 'n'],
    ['土地', 'tǔdì', 'Boden, Land', 'n'],
    ['海洋', 'hǎiyáng', 'Ozean', 'n'],
    ['岛', 'dǎo', 'Insel', 'n'],
    ['平原', 'píngyuán', 'Ebene', 'n'],
    ['高原', 'gāoyuán', 'Hochebene', 'n'],
    ['地震', 'dìzhèn', 'Erdbeben', 'n'],
    ['种植', 'zhòngzhí', 'anpflanzen', 'v'],
    ['农业', 'nóngyè', 'Landwirtschaft', 'n']
  ],

  technik: [
    ['技术', 'jìshù', 'Technik, Technologie', 'n'],
    ['数据', 'shùjù', 'Daten', 'n'],
    ['网络', 'wǎngluò', 'Netzwerk, Internet', 'n'],
    ['信号', 'xìnhào', 'Signal', 'n'],
    ['系统', 'xìtǒng', 'System', 'n'],
    ['程序', 'chéngxù', 'Programm, Ablauf', 'n'],
    ['应用', 'yìngyòng', 'Anwendung, anwenden', 'n'],
    ['功能', 'gōngnéng', 'Funktion', 'n'],
    ['设置', 'shèzhì', 'Einstellung, einstellen', 'n'],
    ['更新', 'gēngxīn', 'aktualisieren', 'v', 'Ruǎnjiàn xūyào gēngxīn.', 'Die Software muss aktualisiert werden.', '软件需要更新。'],
    ['备份', 'bèifèn', 'Sicherungskopie', 'n'],
    ['账号', 'zhànghào', 'Benutzerkonto', 'n'],
    ['登录', 'dēnglù', 'sich anmelden', 'v'],
    ['搜索', 'sōusuǒ', 'suchen (im Netz)', 'v'],
    ['浏览', 'liúlǎn', 'durchsehen, browsen', 'v'],
    ['社交媒体', 'shèjiāo méitǐ', 'soziale Medien', 'n'],
    ['直播', 'zhíbō', 'Livestream', 'n'],
    ['评论', 'pínglùn', 'Kommentar, kommentieren', 'n'],
    ['分享', 'fēnxiǎng', 'teilen', 'v'],
    ['虚拟', 'xūnǐ', 'virtuell', 'a'],
    ['人工智能', 'réngōng zhìnéng', 'künstliche Intelligenz', 'n'],
    ['机器人', 'jīqìrén', 'Roboter', 'n'],
    ['隐私', 'yǐnsī', 'Privatsphäre', 'n'],
    ['病毒', 'bìngdú', 'Virus', 'n']
  ],

  gefuehle: [
    ['情绪', 'qíngxù', 'Gemütslage, Stimmung', 'n'],
    ['心情', 'xīnqíng', 'Laune', 'n', 'Jīntiān wǒ xīnqíng bú tài hǎo.', 'Heute bin ich nicht besonders gut gelaunt.', '今天我心情不太好。'],
    ['性格', 'xìnggé', 'Charakter', 'n'],
    ['乐观', 'lèguān', 'optimistisch', 'a'],
    ['悲观', 'bēiguān', 'pessimistisch', 'a'],
    ['自信', 'zìxìn', 'selbstbewusst', 'a'],
    ['害羞', 'hàixiū', 'schüchtern', 'a'],
    ['幽默', 'yōumò', 'humorvoll', 'a'],
    ['温柔', 'wēnróu', 'sanft', 'a'],
    ['严格', 'yángé', 'streng', 'a'],
    ['固执', 'gùzhi', 'stur', 'a'],
    ['宽容', 'kuānróng', 'nachsichtig', 'a'],
    ['慷慨', 'kāngkǎi', 'großzügig', 'a'],
    ['小气', 'xiǎoqi', 'kleinlich, geizig', 'a'],
    ['积极', 'jījí', 'aktiv, positiv', 'a'],
    ['消极', 'xiāojí', 'passiv, negativ', 'a'],
    ['失望', 'shīwàng', 'enttäuscht', 'a'],
    ['后悔', 'hòuhuǐ', 'bereuen', 'v'],
    ['嫉妒', 'jídù', 'eifersüchtig sein', 'v'],
    ['孤独', 'gūdú', 'einsam', 'a'],
    ['安慰', 'ānwèi', 'trösten', 'v'],
    ['鼓励', 'gǔlì', 'ermutigen', 'v', 'Lǎoshī gǔlì wǒmen duō liànxí.', 'Der Lehrer ermutigt uns, viel zu üben.', '老师鼓励我们多练习。'],
    ['佩服', 'pèifú', 'bewundern', 'v'],
    ['讨厌', 'tǎoyàn', 'nicht ausstehen können', 'v'],
    ['羡慕', 'xiànmù', 'beneiden', 'v'],
    ['同情', 'tóngqíng', 'Mitgefühl haben', 'v']
  ],

  farben: [
    ['色彩', 'sècǎi', 'Farbgebung, Kolorit', 'n'],
    ['鲜艳', 'xiānyàn', 'leuchtend, kräftig (Farbe)', 'a'],
    ['单调', 'dāndiào', 'eintönig', 'a'],
    ['透明', 'tòumíng', 'durchsichtig', 'a'],
    ['直线', 'zhíxiàn', 'gerade Linie', 'n'],
    ['曲线', 'qūxiàn', 'Kurve', 'n'],
    ['对称', 'duìchèn', 'symmetrisch', 'a'],
    ['面积', 'miànjī', 'Fläche', 'n'],
    ['体积', 'tǐjī', 'Volumen', 'n'],
    ['比例', 'bǐlì', 'Verhältnis, Anteil', 'n']
  ],

  stadt: [
    ['市中心', 'shìzhōngxīn', 'Stadtzentrum', 'n'],
    ['郊区', 'jiāoqū', 'Vorort', 'n'],
    ['居民', 'jūmín', 'Einwohner', 'n'],
    ['社区', 'shèqū', 'Wohngemeinde, Community', 'n'],
    ['政府', 'zhèngfǔ', 'Regierung, Behörde', 'n'],
    ['办理', 'bànlǐ', 'erledigen, abwickeln', 'v', 'Wǒ qù bànlǐ jūliú xǔkě.', 'Ich lasse meine Aufenthaltserlaubnis ausstellen.', '我去办理居留许可。'],
    ['手续', 'shǒuxù', 'Formalitäten', 'n'],
    ['证件', 'zhèngjiàn', 'Ausweisdokument', 'n'],
    ['登记', 'dēngjì', 'registrieren', 'v'],
    ['排队', 'páiduì', 'Schlange stehen', 'v'],
    ['公共', 'gōnggòng', 'öffentlich', 'a'],
    ['设施', 'shèshī', 'Einrichtung, Infrastruktur', 'n'],
    ['建筑', 'jiànzhù', 'Gebäude, Architektur', 'n'],
    ['古老', 'gǔlǎo', 'uralt', 'a'],
    ['现代', 'xiàndài', 'modern, Moderne', 'a'],
    ['发展', 'fāzhǎn', 'sich entwickeln, Entwicklung', 'v'],
    ['规划', 'guīhuà', 'Planung, planen', 'n'],
    ['噪音', 'zàoyīn', 'Lärm', 'n'],
    ['治安', 'zhì\'ān', 'öffentliche Sicherheit', 'n'],
    ['村子', 'cūnzi', 'Dorf', 'n'],
    ['城乡', 'chéngxiāng', 'Stadt und Land', 'n'],
    ['迁移', 'qiānyí', 'umsiedeln, migrieren', 'v']
  ],

  feste: [
    ['端午节', 'Duānwǔjié', 'Drachenbootfest', 'n'],
    ['元宵节', 'Yuánxiāojié', 'Laternenfest', 'n'],
    ['国庆节', 'Guóqìngjié', 'Nationalfeiertag', 'n'],
    ['清明节', 'Qīngmíngjié', 'Totengedenkfest', 'n'],
    ['风俗', 'fēngsú', 'Brauch, Sitte', 'n', 'Měi ge dìfang de fēngsú dōu bù yíyàng.', 'Die Bräuche sind überall anders.', '每个地方的风俗都不一样。'],
    ['习俗', 'xísú', 'Gepflogenheit', 'n'],
    ['祖先', 'zǔxiān', 'Vorfahren', 'n'],
    ['祝福', 'zhùfú', 'Segenswunsch, wünschen', 'n'],
    ['对联', 'duìlián', 'Spruchpaar (Neujahr)', 'n'],
    ['舞龙', 'wǔlóng', 'Drachentanz', 'n'],
    ['农历', 'nónglì', 'Mondkalender', 'n'],
    ['庙会', 'miàohuì', 'Tempelmarkt', 'n'],
    ['敬', 'jìng', 'ehren, zuprosten', 'v'],
    ['干杯', 'gānbēi', 'Prost!', 'v'],
    ['拜访', 'bàifǎng', 'einen Besuch abstatten', 'v'],
    ['象征', 'xiàngzhēng', 'Symbol, symbolisieren', 'n']
  ],

  meinung: [
    ['观点', 'guāndiǎn', 'Standpunkt', 'n', 'Wǒ tóngyì nǐ de guāndiǎn.', 'Ich stimme deinem Standpunkt zu.', '我同意你的观点。'],
    ['意见', 'yìjiàn', 'Meinung, Einwand', 'n'],
    ['同意', 'tóngyì', 'zustimmen', 'v'],
    ['反对', 'fǎnduì', 'ablehnen, dagegen sein', 'v'],
    ['赞成', 'zànchéng', 'befürworten', 'v'],
    ['怀疑', 'huáiyí', 'bezweifeln', 'v'],
    ['认为', 'rènwéi', 'der Ansicht sein', 'v'],
    ['看法', 'kànfǎ', 'Sichtweise', 'n'],
    ['理由', 'lǐyóu', 'Grund', 'n'],
    ['原因', 'yuányīn', 'Ursache', 'n'],
    ['结果', 'jiéguǒ', 'Ergebnis, Folge', 'n'],
    ['影响', 'yǐngxiǎng', 'Einfluss, beeinflussen', 'n'],
    ['优点', 'yōudiǎn', 'Vorteil, Stärke', 'n'],
    ['缺点', 'quēdiǎn', 'Nachteil, Schwäche', 'n'],
    ['比较', 'bǐjiào', 'vergleichen, relativ', 'v'],
    ['区别', 'qūbié', 'Unterschied', 'n'],
    ['相同', 'xiāngtóng', 'gleich, identisch', 'a'],
    ['举例说明', 'jǔlì shuōmíng', 'anhand eines Beispiels erläutern', 'v'],
    ['强调', 'qiángdiào', 'betonen', 'v'],
    ['补充', 'bǔchōng', 'ergänzen', 'v'],
    ['承认', 'chéngrèn', 'zugeben, anerkennen', 'v'],
    ['否认', 'fǒurèn', 'bestreiten', 'v'],
    ['说服', 'shuōfú', 'überzeugen', 'v'],
    ['争论', 'zhēnglùn', 'streiten, debattieren', 'v'],
    ['妥协', 'tuǒxié', 'Kompromiss schließen', 'v'],
    ['其实', 'qíshí', 'eigentlich, tatsächlich', 'd'],
    ['确实', 'quèshí', 'wirklich, in der Tat', 'd'],
    ['总之', 'zǒngzhī', 'kurzum, alles in allem', 'd'],
    ['另外', 'lìngwài', 'außerdem', 'd'],
    ['不过', 'búguò', 'allerdings, jedoch', 'd']
  ],

  nachrichten: [
    ['新闻', 'xīnwén', 'Nachricht, Nachrichten', 'n'],
    ['媒体', 'méitǐ', 'Medien', 'n'],
    ['记者', 'jìzhě', 'Journalist', 'n'],
    ['报道', 'bàodào', 'Bericht, berichten', 'n', 'Bàozhǐ bàodào le zhè jiàn shì.', 'Die Zeitung hat über diese Sache berichtet.', '报纸报道了这件事。'],
    ['采访', 'cǎifǎng', 'Interview führen', 'v'],
    ['事件', 'shìjiàn', 'Ereignis, Vorfall', 'n'],
    ['社会', 'shèhuì', 'Gesellschaft', 'n'],
    ['人们', 'rénmen', 'die Leute', 'n'],
    ['公众', 'gōngzhòng', 'Öffentlichkeit', 'n'],
    ['调查', 'diàochá', 'Untersuchung, untersuchen', 'n'],
    ['统计', 'tǒngjì', 'Statistik, statistisch erfassen', 'n'],
    ['现象', 'xiànxiàng', 'Phänomen', 'n'],
    ['趋势', 'qūshì', 'Tendenz, Trend', 'n'],
    ['困境', 'kùnjìng', 'Notlage, Dilemma', 'n'],
    ['解决办法', 'jiějué bànfǎ', 'Lösungsweg', 'n'],
    ['关注', 'guānzhù', 'Beachtung schenken', 'v']
  ],

  wirtschaft: [
    ['经济', 'jīngjì', 'Wirtschaft', 'n'],
    ['市场经济', 'shìchǎng jīngjì', 'Marktwirtschaft', 'n'],
    ['企业', 'qǐyè', 'Unternehmen', 'n'],
    ['产品', 'chǎnpǐn', 'Produkt', 'n'],
    ['生产', 'shēngchǎn', 'produzieren', 'v'],
    ['销售', 'xiāoshòu', 'Vertrieb, verkaufen', 'v', 'Zhè kuǎn chǎnpǐn xiāoshòu hěn hǎo.', 'Dieses Produkt verkauft sich sehr gut.', '这款产品销售很好。'],
    ['成本', 'chéngběn', 'Kosten', 'n'],
    ['利润', 'lìrùn', 'Gewinn', 'n'],
    ['投资', 'tóuzī', 'investieren, Investition', 'v'],
    ['贸易', 'màoyì', 'Handel', 'n'],
    ['出口', 'chūkǒu', 'Export, exportieren', 'n'],
    ['进口', 'jìnkǒu', 'Import, importieren', 'n'],
    ['竞争', 'jìngzhēng', 'Wettbewerb, konkurrieren', 'n'],
    ['客户', 'kèhù', 'Kunde (geschäftlich)', 'n'],
    ['谈判', 'tánpàn', 'verhandeln', 'v'],
    ['签约', 'qiānyuē', 'einen Vertrag unterzeichnen', 'v']
  ]

});
